indigoX: Fragment Class Reference
Fragment Class Reference
Fragment class for CherryPicker parameterisation algorithm.
#include <indigox/classes/athenaeum.hpp>
Classes
struct FragmentData
Public Types
using AngType = stdx::triple< AtmType >
using AtmType = graph::MGVertex
using BndType = std::pair< AtmType, AtmType >
using DhdType = stdx::quad< AtmType >
enum OverlapType
Type of overlapping vertex.
using OverlapVertex = std::pair< OverlapType, graph::CMGVertex >
Type used to match an overlap vertex to its type of overlap.
using Vert = graph::MGVertex
Public Member Functions
Fragment ()=default
Fragment (const Fragment &)=default
Fragment (Fragment &&)=default
Fragment (const graph::MolecularGraph &G, std::vector< graph::MGVertex > &frag, std::vector< graph::MGVertex > &overlap)
Normal constructor.
Fragment (const Molecule &mol, std::vector< Atom > &frag, std::vector< Atom > &overlap)
~ Fragment ()=default
const std::vector< AngType > & GetAngles () const
const std::vector< AtmType > & GetAtoms () const
const std::vector< BndType > & GetBonds () const
const std::vector< DhdType > & GetDihedrals () const
const std::vector< graph::CMGVertex > & GetFragment () const
const graph::CondensedMolecularGraph & GetGraph () const
const std::vector< OverlapVertex > & GetOverlap () const
const boost::dynamic_bitset & GetSupersets () const
bool IsFragmentVertex (const graph::CMGVertex &v) const
bool IsOverlapVertex (const graph::CMGVertex &v) const
operator bool () const
bool operator!= (const Fragment &frag) const
bool operator< (const Fragment &frag) const
bool operator<= (const Fragment &frag) const
Fragment & operator= (Fragment &&)=default
Fragment & operator= (const Fragment &)=default
bool operator== (const Fragment &frag) const
bool operator> (const Fragment &frag) const
bool operator>= (const Fragment &frag) const
size_t Size () const
Private Member Functions
template<class Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< FragmentData > m_data
Friends
class Athenaeum
class cereal::access
std::ostream & operator<< (std::ostream &os, const Fragment &frag)
Detailed Description
Fragment class for CherryPicker parameterisation algorithm.
Member Typedef Documentation
AngType
using AngType = stdx::triple<AtmType>
AtmType
using AtmType = graph::MGVertex
BndType
using BndType = std::pair<AtmType, AtmType>
DhdType
using DhdType = stdx::quad<AtmType>
OverlapVertex
using OverlapVertex = std::pair<OverlapType, graph::CMGVertex>
Type used to match an overlap vertex to its type of overlap.
Vert
using Vert = graph::MGVertex
Member Enumeration Documentation
OverlapType
enum OverlapType strong
Type of overlapping vertex.
Each vertex of an overlap is given a type. This is to enable more detailed isomorphism matching methods to be used when matching.
Enumerator
GenericOverlap
Constructor & Destructor Documentation
Fragment() [1/5]
Fragment () default
Fragment() [2/5]
Fragment (const Fragment &) default
Fragment() [3/5]
Fragment (Fragment &&) default
~ Fragment()
~ Fragment () default
Fragment() [4/5]
Fragment (const graph::MolecularGraph & G, std::vector< graph::MGVertex > & frag, std::vector< graph::MGVertex > & overlap)
Normal constructor.
Constructs a fragment of the given graph from the combined fragment and overlap vertices.
Parameters
G the graph to generate fragment from.
frag the vertices of G that are part of the fragment.
overlap the vertices of G that are part of the overlap region.
Fragment() [5/5]
Fragment (const Molecule & mol, std::vector< Atom > & frag, std::vector< Atom > & overlap)
Member Function Documentation
GetAngles()
const std::vector< Fragment::AngType > & GetAngles () const
Referenced by CherryPickerCallback::operator()().
GetAtoms()
const std::vector< Fragment::AtmType > & GetAtoms () const
Referenced by CherryPickerCallback::operator()().
GetBonds()
const std::vector< Fragment::BndType > & GetBonds () const
Referenced by CherryPickerCallback::operator()().
GetDihedrals()
const std::vector< Fragment::DhdType > & GetDihedrals () const
Referenced by CherryPickerCallback::operator()().
GetFragment()
const std::vector< graph::CMGVertex > & GetFragment () const
GetGraph()
const graph::CondensedMolecularGraph & GetGraph () const
Referenced by Athenaeum::AddFragment(), CherryPickerCallback::operator()(), CherryPicker::ParameteriseMolecule(), and Athenaeum::SortAndMask().
GetOverlap()
const std::vector< Fragment::OverlapVertex > & GetOverlap () const
GetSupersets()
const boost::dynamic_bitset & GetSupersets () const
Referenced by CherryPicker::ParameteriseMolecule().
IsFragmentVertex()
bool IsFragmentVertex (const graph::CMGVertex & v) const
IsOverlapVertex()
bool IsOverlapVertex (const graph::CMGVertex & v) const
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const Fragment & frag) const inline
operator<()
bool operator< (const Fragment & frag) const
operator<=()
bool operator<= (const Fragment & frag) const inline
operator=() [1/2]
Fragment& operator= (Fragment &&) default
operator=() [2/2]
Fragment& operator= (const Fragment &) default
operator==()
bool operator== (const Fragment & frag) const
operator>()
bool operator> (const Fragment & frag) const
operator>=()
bool operator>= (const Fragment & frag) const inline
serialise()
void serialise (Archive & archive, const uint32_t version) private
Size()
size_t Size () const
Referenced by CherryPicker::ParameteriseMolecule().
Friends And Related Function Documentation
Athenaeum
friend class Athenaeum friend
cereal::access
friend class cereal::access friend
operator<<
std::ostream& operator<< (std::ostream & os, const Fragment & frag) friend
Member Data Documentation
m_data
std::shared_ptr<FragmentData> m_data private
Referenced by Fragment::Fragment(), Fragment::GetAngles(), Fragment::GetAtoms(), Fragment::GetBonds(), Fragment::GetDihedrals(), Fragment::GetFragment(), Fragment::GetGraph(), Fragment::GetOverlap(), Fragment::GetSupersets(), Fragment::IsFragmentVertex(), Fragment::IsOverlapVertex(), Fragment::operator<(), indigox::operator<<(), Fragment::operator==(), Fragment::operator>(), Fragment::serialise(), Fragment::Size(), and Athenaeum::SortAndMask().
The documentation for this class was generated from the following files:
include/indigox/classes/athenaeum.hpp
src/classes/athenaeum.cpp