indigoX: ParamAtom Class Reference
ParamAtom Class Reference
#include <indigox/classes/parameterised.hpp>
Classes
struct ParamAtomImpl
Public Types
using MappedCharge = std::vector< double >
Type giving all mapped charges.
using TypeCounts = eastl::vector_map< FFAtom, size_t >
Type giving counts of each mapped atom type.
Public Member Functions
ParamAtom ()=default
ParamAtom (const ParamAtom &)=default
ParamAtom (ParamAtom &&)=default
ParamAtom (const Atom &atm)
Normal constructor.
~ ParamAtom ()=default
bool ApplyParameterisation (bool self_consistent)
Apply the parameterisation.
const Atom & GetAtom () const
Get the atom this parameterises.
const MappedCharge & GetMappedCharges () const
const TypeCounts & GetMappedTypeCounts () const
const FFAtom & GetMostCommonType () const
Get the mode of mapped atom types.
void MappedWith (const Atom &mapped)
Obtain details from mapped atom.
double MeadianCharge ()
Get the median of the charges.
double MeanCharge () const
Get the mean of the charges.
int64_t NumSourceAtoms () const
Calculates the number of mapped atoms.
operator bool () const
bool operator!= (const ParamAtom &atm) const
bool operator< (const ParamAtom &atm) const
bool operator<= (const ParamAtom &atm) const
ParamAtom & operator= (ParamAtom &&)=default
ParamAtom & operator= (const ParamAtom &)=default
bool operator== (const ParamAtom &atm) const
bool operator> (const ParamAtom &atm) const
bool operator>= (const ParamAtom &atm) const
double StandardDeviationCharge () const
Get the standard deviation of the charges.
Private Attributes
std::shared_ptr< ParamAtomImpl > m_data
Friends
std::ostream & operator<< (std::ostream &os, const ParamAtom &atm)
class ParamMolecule
Member Typedef Documentation
MappedCharge
using MappedCharge = std::vector<double>
Type giving all mapped charges.
TypeCounts
using TypeCounts = eastl::vector_map<FFAtom, size_t>
Type giving counts of each mapped atom type.
Constructor & Destructor Documentation
ParamAtom() [1/4]
ParamAtom () default
ParamAtom() [2/4]
ParamAtom (const ParamAtom &) default
ParamAtom() [3/4]
ParamAtom (ParamAtom &&) default
~ ParamAtom()
~ ParamAtom () default
ParamAtom() [4/4]
ParamAtom (const Atom & atm)
Normal constructor.
Parameters
atm the Atom this is parameterising.
Member Function Documentation
ApplyParameterisation()
bool ApplyParameterisation (bool self_consistent)
Apply the parameterisation.
Applies the parameteristion. Doing so sets the partial charge on the atom to the mean of the charge, and the atom type to the most common type. Additionally, doing so will mean that no more atoms can be mapped with. If the self_consistent flag is true, there is a requirement that all the mapped atoms have the same parameters. As such, if there arises a situtation where this requirement is not met, an exception will be thrown.
Parameters
self_consistent if the parameterisation needs to be self consistent.
Referenced by ParamMolecule::ApplyParameteristion().
GetAtom()
const Atom & GetAtom () const
Get the atom this parameterises.
Returns
the atom this parameterises.
Referenced by indigox::operator<<().
GetMappedCharges()
const ParamAtom::MappedCharge & GetMappedCharges () const
GetMappedTypeCounts()
const ParamAtom::TypeCounts & GetMappedTypeCounts () const
GetMostCommonType()
const FFAtom & GetMostCommonType () const
Get the mode of mapped atom types.
Returns
the most commonly mapped atom type.
Referenced by ParamAtom::ApplyParameterisation().
MappedWith()
void MappedWith (const Atom & mapped)
Obtain details from mapped atom.
Parameters
mapped the atom matched.
Referenced by CherryPickerCallback::operator()().
MeadianCharge()
double MeadianCharge ()
Get the median of the charges.
Returns
the median of the charges.
Referenced by ParamAtom::ApplyParameterisation().
MeanCharge()
double MeanCharge () const
Get the mean of the charges.
Returns
the mean of the charges.
Referenced by ParamAtom::ApplyParameterisation().
NumSourceAtoms()
int64_t NumSourceAtoms () const
Calculates the number of mapped atoms.
Returns
the number of atoms which have currently been mapped to me.
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const ParamAtom & atm) const inline
operator<()
bool operator< (const ParamAtom & atm) const
operator<=()
bool operator<= (const ParamAtom & atm) const inline
operator=() [1/2]
ParamAtom& operator= (const ParamAtom &) default
operator=() [2/2]
ParamAtom& operator= (ParamAtom &&) default
operator==()
bool operator== (const ParamAtom & atm) const
operator>()
bool operator> (const ParamAtom & atm) const
operator>=()
bool operator>= (const ParamAtom & atm) const inline
StandardDeviationCharge()
double StandardDeviationCharge () const
Get the standard deviation of the charges.
Returns
the standard deviation of the charges.
Referenced by ParamAtom::ApplyParameterisation().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ParamAtom & atm) friend
ParamMolecule
friend class ParamMolecule friend
Member Data Documentation
m_data
std::shared_ptr<ParamAtomImpl> m_data private
Referenced by ParamAtom::ApplyParameterisation(), ParamAtom::GetAtom(), ParamAtom::GetMappedCharges(), ParamAtom::GetMappedTypeCounts(), ParamAtom::GetMostCommonType(), ParamAtom::MappedWith(), ParamAtom::MeadianCharge(), ParamAtom::MeanCharge(), ParamAtom::NumSourceAtoms(), ParamAtom::operator<(), ParamAtom::operator==(), ParamAtom::operator>(), and ParamAtom::StandardDeviationCharge().
The documentation for this class was generated from the following files:
include/indigox/classes/parameterised.hpp
src/classes/parameterised.cpp