indigoX: Atom Class Reference
Atom Class Reference
#include <indigox/classes/atom.hpp>
Classes
struct Impl
Public Types
using AtomAngles = std::vector< Angle >
Container for storing IXAngle references.
using AtomBonds = std::vector< Bond >
Container for storing Bond references.
using AtomDihedrals = std::vector< Dihedral >
Container for storing IXDihedral references.
enum Stereo
Enum for the different types of atom stereochemistry.
Public Member Functions
Atom ()=default
Atom (const Atom &)=default
Atom (Atom &&)=default
~ Atom ()=default
int32_t AddImplicitHydrogen ()
Add an implicit hydrogen.
const AtomAngles & GetAngles () const
const AtomBonds & GetBonds () const
int32_t GetChargeGroupID () const
const AtomDihedrals & GetDihedrals () const
const Element & GetElement () const
Element of the atom.
int32_t GetFormalCharge () const
Formal charge on the atom.
int64_t GetID () const
int32_t GetImplicitCount () const
Get number of implicit hydrogens.
int64_t GetIndex () const
Get the index from the molecule.
const Molecule & GetMolecule () const
Molecule this atom is associated with.
const std::string & GetName () const
Atom name.
double GetPartialCharge () const
Partial atomic charge on the atom.
const Eigen::Vector3d & GetPosition () const
Vector of the atom's position.
int32_t GetResidueID ()
std::string GetResidueName ()
Stereo GetStereochemistry () const
Get the stereochemistry of the atom.
int64_t GetTag () const
Tag of the atom.
const FFAtom & GetType () const
Get the FF type of the atom.
double GetX () const
Atom x position.
double GetY () const
Atom y position.
double GetZ () const
Atom z position.
bool HasType () const
int64_t NumAngles () const
Number of valid angles this atom is a part of.
int64_t NumBonds () const
Number of valid bonds this atom is part of.
int64_t NumDihedrals () const
Number of valid dihedrals this atom is a part of.
int32_t NumHeavyAtomBonds () const
int32_t NumHydrogenBonds () const
operator bool () const
bool operator!= (const Atom &atm) const
bool operator< (const Atom &atm) const
bool operator<= (const Atom &atm) const
Atom & operator= (const Atom &)=default
Atom & operator= (Atom &&)=default
bool operator== (const Atom &atm) const
bool operator> (const Atom &atm) const
bool operator>= (const Atom &atm) const
int32_t RemoveImplicitHydrogen ()
Remove an implicit hydrogen.
void SetChargeGroupID (int32_t id)
void SetElement (const Element &e)
Set the element of this atom.
void SetElement (std::string e)
Set the element of this atom.
void SetElement (int32_t e)
Set the element of this atom.
void SetFormalCharge (int32_t q)
Set the formal charge of this atom.
void SetImplicitCount (int32_t h)
Set the number of implicit hydrogens.
void SetName (std::string n)
Set the atom name.
void SetPartialCharge (double q)
Set the partial charge of this atom.
void SetPosition (double x, double y, double z)
Set the x, y and z positions.
void SetStereochemistry (Stereo s)
Set the stereochemistry of an atomic center.
void SetTag (int32_t i)
Set the tag of this atom.
void SetType (const FFAtom &type)
Set the FF type of the atom.
Private Member Functions
Atom (const Molecule &molecule, const Element &element, double x, double y, double z, std::string name)
Normal constructor.
void AddAngle (const Angle &a)
Add an angle to this atom.
void AddBond (const Bond &b)
Add a bond to this atom.
void AddDihedral (const Dihedral &d)
Add a dihedral to this atom.
void RemoveAngle (const Angle &a)
Remove an angle from this atom.
void RemoveBond (const Bond &b)
Remove a bond from this atom.
void RemoveDihedral (const Dihedral &d)
Remove a dihedral from this atom.
void Reset ()
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows IXAtom to be serialised.
class indigox::Molecule
Friendship allows IXMolecule to create new atoms.
std::ostream & operator<< (std::ostream &os, const Atom &atm)
Member Typedef Documentation
AtomAngles
using AtomAngles = std::vector<Angle>
Container for storing IXAngle references.
AtomBonds
using AtomBonds = std::vector<Bond>
Container for storing Bond references.
AtomDihedrals
using AtomDihedrals = std::vector<Dihedral>
Container for storing IXDihedral references.
Member Enumeration Documentation
Stereo
enum Stereo strong
Enum for the different types of atom stereochemistry.
Enumerator
UNDEFINED
No defined stereochemistry.
ACHIRAL
Defined as no stereochemistry.
R
Has R stereochemistry.
S
Has S stereochemistry.
Constructor & Destructor Documentation
Atom() [1/4]
Atom () default
Atom() [2/4]
Atom (const Atom &) default
Atom() [3/4]
Atom (Atom &&) default
~ Atom()
~ Atom () default
Atom() [4/4]
Atom (const Molecule & molecule, const Element & element, double x, double y, double z, std::string name) private
Normal constructor.
Links the constructed atom to the given Molecule.
Parameters
m the molecule to assign this atom to.
Member Function Documentation
AddAngle()
void AddAngle (const Angle & a) private
Add an angle to this atom.
Assumes that the angle is not already added to the atom.
Parameters
a the angle to add.
Returns
if the angle was added or not.
AddBond()
void AddBond (const Bond & b) private
Add a bond to this atom.
Assumes that the bond is not already added to the atom.
Parameters
b the bond to add.
Returns
if the bond was added or not.
AddDihedral()
void AddDihedral (const Dihedral & d) private
Add a dihedral to this atom.
Assumes that the dihedral is not already added to the atom.
Parameters
d the dihedral to add.
Returns
if the dihedral was added or not.
AddImplicitHydrogen()
int32_t AddImplicitHydrogen ()
Add an implicit hydrogen.
Returns
the new number of implicit hydrogens in the atom.
GetAngles()
const Atom::AtomAngles & GetAngles () const
Referenced by Molecule::Impl::FindAngle(), and Molecule::GetAngle().
GetBonds()
const Atom::AtomBonds & GetBonds () const
Referenced by Molecule::Impl::FindBond(), Molecule::GetBond(), Bond::IsAmideBond(), Molecule::NewBond(), Atom::NumHydrogenBonds(), Molecule::PerceiveDihedrals(), and Molecule::RemoveBond().
GetChargeGroupID()
int32_t GetChargeGroupID () const
GetDihedrals()
const Atom::AtomDihedrals & GetDihedrals () const
Referenced by Molecule::Impl::FindDihedral(), Molecule::GetDihedral(), Molecule::NewDihedral(), and Molecule::PerceiveDihedrals().
GetElement()
const Element & GetElement () const
Element of the atom.
Returns
the element of this atom.
Referenced by IXElectronAssigner::AssignAlgorithm::ApplyAssignment(), CMGVertex::CMGVertex(), indigox::graph::Condense(), Molecule::GetFormula(), indigox::algorithm::GetVertexSortOrder(), IXElectronAssigner::AssignAlgorithm::Initalise(), CMGVertex::IsContractedHere(), and Molecule::PerceiveDihedrals().
GetFormalCharge()
int32_t GetFormalCharge () const
Formal charge on the atom.
Returns
the formal charge on the atom.
Referenced by CMGVertex::CMGVertex(), indigox::graph::Condense(), and ChargeGroupOptimiser::Initalise().
GetID()
int64_t GetID () const
Referenced by Molecule::GetAtomID().
GetImplicitCount()
int32_t GetImplicitCount () const
Get number of implicit hydrogens.
Returns
the number of implicit hydrogens in the atom.
Referenced by CMGVertex::CMGVertex(), Bond::IsAmideBond(), and Bond::IsCarbonylBond().
GetIndex()
int64_t GetIndex () const
Get the index from the molecule.
Calculates the index of the atom in the container of atoms of the molecule it is a part of. If the molecule is dead, the index returned is the tag of the atom.
Returns
the index of the atom.
Referenced by indigox::operator<<(), and indigox::graph::operator<<().
GetMolecule()
const Molecule & GetMolecule () const
Molecule this atom is associated with.
The returned shared_ptr is empty of the atom is not assigned to a valid molecule.
Returns
the molecule associated with this atom.
Referenced by Molecule::HasAtom().
GetName()
const std::string & GetName () const
Atom name.
Returns
name of the atom.
GetPartialCharge()
double GetPartialCharge () const
Partial atomic charge on the atom.
Returns
the partial atomic charge.
Referenced by ChargeGroupOptimiser::Initalise(), and ParamAtom::MappedWith().
GetPosition()
const Eigen::Vector3d & GetPosition () const
Vector of the atom's position.
Returns
the atoms position.
GetResidueID()
int32_t GetResidueID ()
GetResidueName()
std::string GetResidueName ()
GetStereochemistry()
AtomStereo GetStereochemistry () const
Get the stereochemistry of the atom.
Returns
the stereochemistry of the atom.
Referenced by CMGVertex::CMGVertex().
GetTag()
int64_t GetTag () const
Tag of the atom.
This value may be modified without warning. Use with caution. For a constant identifier to the atom, use IXAtom::GetUniqueID.
Returns
the tag assigned to the atom.
Referenced by Molecule::GetAtomTag().
GetType()
const FFAtom & GetType () const
Get the FF type of the atom.
Returns
the force field type of the atom.
Referenced by ParamAtom::MappedWith().
GetX()
double GetX () const
Atom x position.
Returns
the x coordinate of this atom.
GetY()
double GetY () const
Atom y position.
Returns
the y coordinate of this atom.
GetZ()
double GetZ () const
Atom z position.
Returns
the z coordinate of this atom.
HasType()
bool HasType () const
Referenced by ParamAtom::MappedWith().
NumAngles()
int64_t NumAngles () const
Number of valid angles this atom is a part of.
Returns
the number of valid assigned angles.
Referenced by Molecule::Impl::FindAngle().
NumBonds()
int64_t NumBonds () const
Number of valid bonds this atom is part of.
Returns
the number of valid assigned bonds.
Referenced by CMGEdge::CMGEdge(), CMGVertex::CMGVertex(), Molecule::Impl::FindBond(), indigox::algorithm::GetVertexSortOrder(), Bond::IsAmideBond(), Bond::IsCarbonylBond(), Atom::NumHeavyAtomBonds(), Molecule::PerceiveAngles(), and Molecule::PerceiveDihedrals().
NumDihedrals()
int64_t NumDihedrals () const
Number of valid dihedrals this atom is a part of.
Returns
the number of valid assigned dihedrals.
Referenced by Molecule::Impl::FindDihedral().
NumHeavyAtomBonds()
int32_t NumHeavyAtomBonds () const
NumHydrogenBonds()
int32_t NumHydrogenBonds () const
Referenced by Atom::NumHeavyAtomBonds().
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const Atom & atm) const inline
operator<()
bool operator< (const Atom & atm) const
operator<=()
bool operator<= (const Atom & atm) const inline
operator=() [1/2]
Atom& operator= (const Atom &) default
operator=() [2/2]
Atom& operator= (Atom &&) default
operator==()
bool operator== (const Atom & atm) const
operator>()
bool operator> (const Atom & atm) const
operator>=()
bool operator>= (const Atom & atm) const inline
RemoveAngle()
void RemoveAngle (const Angle & a) private
Remove an angle from this atom.
Assumes that the angle is added to the atom.
Parameters
a the angle to remove.
Returns
if the angle was removed or not.
RemoveBond()
void RemoveBond (const Bond & b) private
Remove a bond from this atom.
Assumes that the bond is added to the atom.
Parameters
b the bond to remove.
Returns
if the bond was removed or not.
Referenced by Molecule::RemoveBond().
RemoveDihedral()
void RemoveDihedral (const Dihedral & d) private
Remove a dihedral from this atom.
Assumes that the dihedral is added to the atom.
Parameters
d the dihedral to remove.
Returns
if the dihedral was removed or not.
RemoveImplicitHydrogen()
int32_t RemoveImplicitHydrogen ()
Remove an implicit hydrogen.
If GetImplicitCount() == 0, no hydrogen is removed.
Returns
the new number of implicit hydrogens in the atom.
Reset()
void Reset () private
Referenced by Molecule::RemoveAtom().
serialise()
void serialise (Archive & archive, const uint32_t version) private
SetChargeGroupID()
void SetChargeGroupID (int32_t id)
SetElement() [1/3]
void SetElement (const Element & e)
Set the element of this atom.
Parameters
e the element to set to.
Referenced by Atom::SetElement().
SetElement() [2/3]
void SetElement (std::string e)
Set the element of this atom.
Parameters
e the name or atomic symbol of the element to set.
SetElement() [3/3]
void SetElement (int32_t e)
Set the element of this atom.
Parameters
e the atomic number of the element to set.
SetFormalCharge()
void SetFormalCharge (int32_t q)
Set the formal charge of this atom.
Parameters
q the formal charge value to set.
Referenced by IXElectronAssigner::AssignAlgorithm::ApplyAssignment(), and ProtonatedLysine().
SetImplicitCount()
void SetImplicitCount (int32_t h)
Set the number of implicit hydrogens.
Parameters
h the number of implicit hydrogens to set.
SetName()
void SetName (std::string n)
Set the atom name.
Parameters
n name to set.
Referenced by Benzene(), and ProtonatedLysine().
SetPartialCharge()
void SetPartialCharge (double q)
Set the partial charge of this atom.
Parameters
q the partial charge value to set.
Referenced by Benzene(), and ProtonatedLysine().
SetPosition()
void SetPosition (double x, double y, double z)
Set the x, y and z positions.
Parameters
x,y,z position to set.
SetStereochemistry()
void SetStereochemistry (Stereo s)
Set the stereochemistry of an atomic center.
Parameters
s the stereochemistry to set.
SetTag()
void SetTag (int32_t i)
Set the tag of this atom.
The tag of an atom should not be considered stable. Use with caution.
Parameters
i the tag to set.
SetType()
void SetType (const FFAtom & type)
Set the FF type of the atom.
Parameters
type the type to set.
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows IXAtom to be serialised.
indigox::Molecule
friend class indigox::Molecule friend
Friendship allows IXMolecule to create new atoms.
operator<<
std::ostream& operator<< (std::ostream & os, const Atom & atm) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by Atom::AddAngle(), Atom::AddBond(), Atom::AddDihedral(), Atom::AddImplicitHydrogen(), Atom::GetAngles(), Atom::GetBonds(), Atom::GetChargeGroupID(), Atom::GetDihedrals(), Atom::GetElement(), Atom::GetFormalCharge(), Atom::GetID(), Atom::GetImplicitCount(), Atom::GetIndex(), Atom::GetMolecule(), Atom::GetName(), Atom::GetPartialCharge(), Atom::GetPosition(), Atom::GetResidueID(), Atom::GetResidueName(), Atom::GetStereochemistry(), Atom::GetTag(), Atom::GetType(), Atom::GetX(), Atom::GetY(), Atom::GetZ(), Atom::HasType(), Molecule::NewAtom(), Atom::NumAngles(), Atom::NumBonds(), Atom::NumDihedrals(), Atom::operator<(), Atom::operator==(), Atom::operator>(), Molecule::PerceiveAngles(), Molecule::PerceiveResidues(), Atom::RemoveAngle(), Molecule::RemoveAtom(), Atom::RemoveBond(), Atom::RemoveDihedral(), Atom::RemoveImplicitHydrogen(), Atom::Reset(), Atom::serialise(), Atom::SetChargeGroupID(), Atom::SetElement(), Atom::SetFormalCharge(), Atom::SetImplicitCount(), Atom::SetName(), Atom::SetPartialCharge(), Atom::SetPosition(), Atom::SetStereochemistry(), Atom::SetTag(), and Atom::SetType().
The documentation for this class was generated from the following files:
include/indigox/classes/atom.hpp
src/classes/atom.cpp