indigoX: FFDihedral Class Reference
FFDihedral Class Reference
#include <indigox/classes/forcefield.hpp>
Classes
struct Impl
Public Types
enum Type
Enum for the different function types a dihedral term can have.
Public Member Functions
FFDihedral ()=default
FFDihedral (const FFDihedral &)=default
FFDihedral (FFDihedral &&)=default
~ FFDihedral ()=default
double GetForceConstant () const
Get the force constant.
Forcefield GetForcefield () const
int32_t GetID () const
Get the ID for this type.
double GetIdealAngle () const
Get the ideal angle (in degrees).
int32_t GetMultiplicity () const
Get the multiplicity.
double GetPhaseShift () const
Get the phase shift (in degrees).
Type GetType () const
Get the potential energy function type.
operator bool () const
bool operator!= (const FFDihedral &dhd) const
bool operator< (const FFDihedral &dhd) const
bool operator<= (const FFDihedral &dhd) const
FFDihedral & operator= (const FFDihedral &)=default
FFDihedral & operator= (FFDihedral &&)=default
bool operator== (const FFDihedral &dhd) const
bool operator> (const FFDihedral &dhd) const
bool operator>= (const FFDihedral &dhd) const
Private Types
using AllowedMask = eastl::bitset< num_allow_positions >
Type used for storing allowed parameters.
enum AllowEnum
Enum giving the allow positions of each parameter type.
using DataStore = std::array< double, STORE_SIZE >
Type used to store all the internal data.
enum StoreEnum
Enum giving the stored index of each parameter type.
Private Member Functions
FFDihedral (Type type, int32_t id, FFParam parameters, const Forcefield &ff)
Normal construtor.
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows serialisation.
class Forcefield
Friendship allows dihedral types to be added to a forcefield.
std::ostream & operator<< (std::ostream &os, const FFDihedral &dhd)
Member Typedef Documentation
AllowedMask
using AllowedMask = eastl::bitset<num_allow_positions> private
Type used for storing allowed parameters.
DataStore
using DataStore = std::array<double, STORE_SIZE> private
Type used to store all the internal data.
Member Enumeration Documentation
AllowEnum
enum AllowEnum private
Enum giving the allow positions of each parameter type.
Enumerator
Allow_PhaseShift
Allow_ForceConstant
Allow_Multiplicity
Allow_IdealAngle
num_allow_positions
StoreEnum
enum StoreEnum private
Enum giving the stored index of each parameter type.
Enumerator
Store_PhaseShift
Store_ForceConstant
Store_Multiplicity
Store_IdealAngle
STORE_SIZE
Type
enum Type strong
Enum for the different function types a dihedral term can have.
Though other values are provided, currently only the proper and improper function types are technically supported.
Enumerator
Empty
Proper
Improper
RyckaertBellemans
PeriodicImproper
Fourier
Restricted
Constructor & Destructor Documentation
FFDihedral() [1/4]
FFDihedral () default
FFDihedral() [2/4]
FFDihedral (const FFDihedral &) default
FFDihedral() [3/4]
FFDihedral (FFDihedral &&) default
~ FFDihedral()
~ FFDihedral () default
FFDihedral() [4/4]
FFDihedral (Type type, int32_t id, FFParam parameters, const Forcefield & ff) private
Normal construtor.
Creates a new dihedral term of the specified type.
Parameters
type the type of the potential energy function to use.
id the ID of the type.
parameters the list of parameters for the function.
ff the forcefield this type will beloing to.
Member Function Documentation
GetForceConstant()
double GetForceConstant () const
Get the force constant.
Returns
the force constant.
Exceptions
std::runtime_error if the type does not allow a force constant.
GetForcefield()
Forcefield GetForcefield () const
Referenced by Dihedral::AddType().
GetID()
int32_t GetID () const
Get the ID for this type.
Returns
the ID of this dihedral type.
Referenced by FFDihedral::operator<(), indigox::operator<<(), FFDihedral::operator==(), and FFDihedral::operator>().
GetIdealAngle()
double GetIdealAngle () const
Get the ideal angle (in degrees).
Returns
the ideal angle.
Exceptions
std::runtime_error if the type does not allow an ideal angle.
GetMultiplicity()
int32_t GetMultiplicity () const
Get the multiplicity.
Returns
the multiplicity.
Exceptions
std::runtime_error if the type does not allow a multiplicity.
GetPhaseShift()
double GetPhaseShift () const
Get the phase shift (in degrees).
Returns
the phase shift.
Exceptions
std::runtime_error if the type does not allow a phase shift.
GetType()
DihedralType GetType () const
Get the potential energy function type.
Returns
the type of the potential energy function.
Referenced by FFDihedral::operator<(), indigox::operator<<(), FFDihedral::operator==(), and FFDihedral::operator>().
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const FFDihedral & dhd) const inline
operator<()
bool operator< (const FFDihedral & dhd) const
operator<=()
bool operator<= (const FFDihedral & dhd) const inline
operator=() [1/2]
FFDihedral& operator= (const FFDihedral &) default
operator=() [2/2]
FFDihedral& operator= (FFDihedral &&) default
operator==()
bool operator== (const FFDihedral & dhd) const
operator>()
bool operator> (const FFDihedral & dhd) const
operator>=()
bool operator>= (const FFDihedral & dhd) const inline
serialise()
void serialise (Archive & archive, const uint32_t version) private
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows serialisation.
Forcefield
friend class Forcefield friend
Friendship allows dihedral types to be added to a forcefield.
operator<<
std::ostream& operator<< (std::ostream & os, const FFDihedral & dhd) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by FFDihedral::GetForceConstant(), FFDihedral::GetForcefield(), FFDihedral::GetID(), FFDihedral::GetIdealAngle(), FFDihedral::GetMultiplicity(), FFDihedral::GetPhaseShift(), FFDihedral::GetType(), FFDihedral::operator==(), and FFDihedral::serialise().
The documentation for this class was generated from the following files:
include/indigox/classes/forcefield.hpp
src/classes/forcefield.cpp