indigoX: Forcefield Class Reference
Forcefield Class Reference
#include <indigox/classes/forcefield.hpp>
Classes
struct Impl
Public Types
enum Family
Enum for the different families of forcefields.
Public Member Functions
Forcefield ()=default
Forcefield (const Forcefield &)=default
Forcefield (Forcefield &&)=default
Forcefield (Family family, std::string name)
Normal constructor.
~ Forcefield ()=default
FFAngle GetAngleType (AngleType type, int32_t id) const
Get the type of angle with the given id.
FFAngle GetAngleType (int32_t id) const
Get the first angle type with the given id.
FFAtom GetAtomType (std::string name) const
Get the AtomType with the given name.
FFAtom GetAtomType (int32_t id) const
Get the AtomType with the given id.
FFBond GetBondType (BondType type, int32_t id) const
Get the type of bond with the given id.
FFBond GetBondType (int32_t id) const
Get the first bond type with the given id.
FFDihedral GetDihedralType (DihedralType type, int32_t id) const
Get the type of dihedral with the given id.
FFDihedral GetDihedralType (int32_t id) const
Get the first dihedral type with the given id.
Family GetFamily () const
Get the family of the forcefield.
std::string GetName () const
Get the name of the forcefield.
void LinkAngleTypes (const FFAngle &a, const FFAngle &b)
Link together two equivalent angle types.
void LinkBondTypes (const FFBond &a, const FFBond &b)
Link together two equivalent bond types.
FFAngle NewAngleType (AngleType type, int32_t id, double a, double b)
Adds a new angle type to the forcefield with two parameters.
FFAtom NewAtomType (int32_t id, std::string name, const Element &element)
Add a new atom type to the forcefield.
FFBond NewBondType (BondType type, int32_t id, double a, double b)
Adds a new bond type to the forcefield with two parameters.
FFDihedral NewDihedralType (DihedralType type, int32_t id, double a, double b, double c)
Adds a new dihedral type to the forcefield with three parameters.
FFDihedral NewDihedralType (DihedralType type, int32_t id, double a, double b)
Adds a new dihedral type to the forcefield with two parameters.
size_t NumAngleTypes () const
Get the number of angle types in the forcefield.
size_t NumAngleTypes (AngleType type) const
Get the number of angle types of the given functional form.
size_t NumAtomTypes () const
Get the number of atom types in the forcefield.
size_t NumBondTypes () const
Get the total number of bond types in the forcefield.
size_t NumBondTypes (BondType type) const
Get the number of bond types of the given functional form.
size_t NumDihedralTypes () const
Get the number of dihedral types in the forcefield.
size_t NumDihedralTypes (DihedralType type) const
Get the number of dihedral types of the given functional form.
operator bool () const
bool operator!= (const Forcefield &ff) const
bool operator< (const Forcefield &ff) const
bool operator<= (const Forcefield &ff) const
Forcefield & operator= (const Forcefield &)=default
Forcefield & operator= (Forcefield &&)=default
bool operator== (const Forcefield &ff) const
bool operator> (const Forcefield &ff) const
bool operator>= (const Forcefield &ff) const
void ReserveAngleTypes (AngleType type, size_t size)
Reserve space for angle types.
void ReserveAtomTypes (size_t size)
Reserve space for atom types.
void ReserveBondTypes (BondType type, size_t size)
Reserve space for bond types.
void ReserveDihedralTypes (DihedralType type, size_t size)
Reserve space for dihedral types.
Private Types
using AngleTypes = std::map< AngleType, std::vector< FFAngle > >
Type used to store the angle types.
using AtomTypes = std::vector< FFAtom >
Type used to store the atom types.
using BondTypes = std::map< BondType, std::vector< FFBond > >
Type used to store the bond types.
using DihedralTypes = std::map< DihedralType, std::vector< FFDihedral > >
Type used to store the dihedral types.
Private Member Functions
FFAngle NewAngleType (AngleType type, int32_t id, FFParam param)
Adds a new angle type to the forcefield.
FFBond NewBondType (BondType type, int32_t id, FFParam param)
Adds a new bond type to the forcefield.
FFDihedral NewDihedralType (DihedralType type, int32_t id, FFParam param)
Adds a new dihedral type to the forcefield.
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows serialisation.
std::ostream & operator<< (std::ostream &os, const Forcefield &ff)
Member Typedef Documentation
AngleTypes
using AngleTypes = std::map<AngleType, std::vector<FFAngle> > private
Type used to store the angle types.
AtomTypes
using AtomTypes = std::vector<FFAtom> private
Type used to store the atom types.
BondTypes
using BondTypes = std::map<BondType, std::vector<FFBond> > private
Type used to store the bond types.
DihedralTypes
using DihedralTypes = std::map<DihedralType, std::vector<FFDihedral> > private
Type used to store the dihedral types.
Member Enumeration Documentation
Family
enum Family strong
Enum for the different families of forcefields.
Though other values are provided, currently only the GROMOS family of forcefields are technically supported.
Enumerator
Empty
GROMOS
CHARMM
AMBER
Other
Constructor & Destructor Documentation
Forcefield() [1/4]
Forcefield () default
Forcefield() [2/4]
Forcefield (const Forcefield &) default
Forcefield() [3/4]
Forcefield (Forcefield &&) default
~ Forcefield()
~ Forcefield () default
Forcefield() [4/4]
Forcefield (Family family, std::string name)
Normal constructor.
Create a new forcefield from the given family. The family dictates which types of functional forms are allowed. Currently implemented is the GROMOS family of forcefields, which allows harmonic and quartic bond types, harmonic and caosine-harmonic angle types, and proper and improper dihedral types.
Parameters
family the family of forcefields to use.
name the name of the forcefield.
Member Function Documentation
GetAngleType() [1/2]
FFAngle GetAngleType (AngleType type, int32_t id) const
Get the type of angle with the given id.
Parameters
type the type of angle to get.
the id of the angle type.
Returns
the requested angle type, or an empty shared_ptr.
GetAngleType() [2/2]
FFAngle GetAngleType (int32_t id) const
Get the first angle type with the given id.
Searches through all allowed angle types in order and returns the first type with the given id.
Parameters
id the id of the angle type.
Returns
the angle type, or an empty shared_ptr.
GetAtomType() [1/2]
FFAtom GetAtomType (std::string name) const
Get the AtomType with the given name.
Parameters
name the name of the atom type.
Returns
the atomtype with the name, or an empty shared_ptr.
GetAtomType() [2/2]
FFAtom GetAtomType (int32_t id) const
Get the AtomType with the given id.
Parameters
id the id of the atom type.
Returns
the atomtype with the id, or an empty shared_ptr.
GetBondType() [1/2]
FFBond GetBondType (BondType type, int32_t id) const
Get the type of bond with the given id.
Parameters
type the type of bond to get.
the id of the bond type.
Returns
the requested bond type, or an empty shared_ptr.
Referenced by Forcefield::GetBondType().
GetBondType() [2/2]
FFBond GetBondType (int32_t id) const
Get the first bond type with the given id.
Searches through all allowed bond types in order and returns the first type with the id.
Parameters
id the id of the bond type.
Returns
the bond type, or an empty shared_ptr.
GetDihedralType() [1/2]
FFDihedral GetDihedralType (DihedralType type, int32_t id) const
Get the type of dihedral with the given id.
Parameters
type the type of dihedral to get.
the id of the dihedral type.
Returns
the requested dihedral type, or an empty shared_ptr.
Referenced by Forcefield::GetDihedralType().
GetDihedralType() [2/2]
FFDihedral GetDihedralType (int32_t id) const
Get the first dihedral type with the given id.
Searches through all allowed dihedral types in order and returns the first type with the given id.
Parameters
id the id of the dihedral type.
Returns
the dihedral type, or an empty shared_ptr.
GetFamily()
FFFamily GetFamily () const
Get the family of the forcefield.
Returns
the forcefields family.
Referenced by Forcefield::operator==().
GetName()
std::string GetName () const
Get the name of the forcefield.
Returns
the name of the forcefield.
Referenced by indigox::operator<<(), and Forcefield::operator==().
LinkAngleTypes()
void LinkAngleTypes (const FFAngle & a, const FFAngle & b)
Link together two equivalent angle types.
Two angle types can be linked together when they are regarded as the same type with different functional forms. For example, the GROMOS forcefield provides both harmonic and cosine-harmonic force constants for all angle types. This method will remove any existing links.
Parameters
a,b the two types to link.
Referenced by indigox::GenerateGROMOS54A7().
LinkBondTypes()
void LinkBondTypes (const FFBond & a, const FFBond & b)
Link together two equivalent bond types.
Two bond types can be linked together when they are regarded as the same type with different functional forms. For example, the GROMOS forcefield provides both harmonic and quartic force constants for all bond types. This method will remove any existing links.
Parameters
a,b the two types to link.
Referenced by indigox::GenerateGROMOS54A7().
NewAngleType() [1/2]
FFAngle NewAngleType (AngleType type, int32_t id, FFParam param) private
Adds a new angle type to the forcefield.
Parameters
type the type of the angle.
id the id of the angle.
parameters the parameters of the angle.
Returns
the newly created angle type.
Referenced by indigox::GenerateGROMOS54A7(), and Forcefield::NewAngleType().
NewAngleType() [2/2]
FFAngle NewAngleType (AngleType type, int32_t id, double a, double b)
Adds a new angle type to the forcefield with two parameters.
This constructor should be used for AngleType::Harmonic and AngleType::CosineHarmonic bond types. In both cases, a is the force constant and b is the ideal angle.
Parameters
type the type of the angle.
id the id of the angle.
a,b the two parameter values.
Returns
the newly created angle type.
NewAtomType()
FFAtom NewAtomType (int32_t id, std::string name, const Element & element)
Add a new atom type to the forcefield.
Parameters
id the id of the atom type.
name the name of the atom type.
Returns
the newly created atom type.
Exceptions
std::runtime_error if an atomtype with the given name or id already exists within the forcefield.
Referenced by indigox::GenerateGROMOS54A7().
NewBondType() [1/2]
FFBond NewBondType (BondType type, int32_t id, FFParam param) private
Adds a new bond type to the forcefield.
Parameters
type the type of the bond.
id the id of the bond.
parameters the parameters of the bond.
Returns
the newly created bond type.
Referenced by indigox::GenerateGROMOS54A7(), and Forcefield::NewBondType().
NewBondType() [2/2]
FFBond NewBondType (BondType type, int32_t id, double a, double b)
Adds a new bond type to the forcefield with two parameters.
This constructor should be used for BondType::Harmonic and BondType::Quartic bond types. In both cases, a is the force constant and b is the ideal length.
Parameters
type the type of the bond.
id the id of the bond.
a,b the two parameter values.
Returns
the newly created bond type.
NewDihedralType() [1/3]
FFDihedral NewDihedralType (DihedralType type, int32_t id, FFParam param) private
Adds a new dihedral type to the forcefield.
Parameters
type the type of the dihedral.
id the id of the dihedral.
parameters the parameters of the dihedral.
Returns
the newly created dihedral type.
Referenced by indigox::GenerateGROMOS54A7(), and Forcefield::NewDihedralType().
NewDihedralType() [2/3]
FFDihedral NewDihedralType (DihedralType type, int32_t id, double a, double b, double c)
Adds a new dihedral type to the forcefield with three parameters.
This constructor should be used for DihedralType::Proper dihedral types. In that case, a is the force constant, b is the phase and c is the multiplicity.
Parameters
type the type of dihedral.
id the id of the dihedral.
a,b,c the three parameter values.
Returns
the newly created dihedral type.
NewDihedralType() [3/3]
FFDihedral NewDihedralType (DihedralType type, int32_t id, double a, double b)
Adds a new dihedral type to the forcefield with two parameters.
This constructor should be used for DihedralType::Improper dihedral types. In that case, a is the force constant and b is the ideal dihedral angle
Parameters
type the type of dihedral.
id the id of the dihedral.
a,b the three parameter values.
Returns
the newly created dihedral type.
NumAngleTypes() [1/2]
size_t NumAngleTypes () const
Get the number of angle types in the forcefield.
For forcefields with multiple allowed types, the count of each type are summed.
Returns
the number of angle types in the forcefield.
NumAngleTypes() [2/2]
size_t NumAngleTypes (AngleType type) const
Get the number of angle types of the given functional form.
Determines how may of the given angle types are present in the forcefield. In the case that the provided type is not supposrted by the forcefield, 0 is returned.
Parameters
type the type of angle to count.
Returns
the number of angle types in the forcefield.
NumAtomTypes()
size_t NumAtomTypes () const
Get the number of atom types in the forcefield.
Returns
the number of atom types in the forcefield.
NumBondTypes() [1/2]
size_t NumBondTypes () const
Get the total number of bond types in the forcefield.
For forcefields with multiple allowed types, the count of each type are summed.
Returns
the number of bond types in the forcefield.
NumBondTypes() [2/2]
size_t NumBondTypes (BondType type) const
Get the number of bond types of the given functional form.
Determines how many of the given bond type funcitonal form are present in the forcefield. In the case that the provided type is not supported by the forcefield, 0 is returned.
Parameters
type the type of bond to count.
Returns
the number of bond types in the forcefield.
NumDihedralTypes() [1/2]
size_t NumDihedralTypes () const
Get the number of dihedral types in the forcefield.
For forcefields with multiple allowed types, the count of each type are summed.
Returns
the number of bond types in the forcefield.
NumDihedralTypes() [2/2]
size_t NumDihedralTypes (DihedralType type) const
Get the number of dihedral types of the given functional form.
Determines how many of the given dihedral types are present in the forcefield. In the case that the provided type is not supported by the forcefield, 0 is returned.
Parameters
type the type of dihedral to count.
Returns
the number of dihedral types in the forcefield.
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const Forcefield & ff) const inline
operator<()
bool operator< (const Forcefield & ff) const
operator<=()
bool operator<= (const Forcefield & ff) const inline
operator=() [1/2]
Forcefield& operator= (Forcefield &&) default
operator=() [2/2]
Forcefield& operator= (const Forcefield &) default
operator==()
bool operator== (const Forcefield & ff) const
operator>()
bool operator> (const Forcefield & ff) const
operator>=()
bool operator>= (const Forcefield & ff) const inline
ReserveAngleTypes()
void ReserveAngleTypes (AngleType type, size_t size)
Reserve space for angle types.
Parameters
type the type of angle to reserve space for.
size the amount of space to reserve.
ReserveAtomTypes()
void ReserveAtomTypes (size_t size)
Reserve space for atom types.
Parameters
size the amount of space to reserve.
ReserveBondTypes()
void ReserveBondTypes (BondType type, size_t size)
Reserve space for bond types.
Parameters
type the type of bond to reserve space for.
size the amount of space to reserve.
ReserveDihedralTypes()
void ReserveDihedralTypes (DihedralType type, size_t size)
Reserve space for dihedral types.
Parameters
type the type of dihedral to reserve space for.
size the amount of space to reserve.
serialise()
void serialise (Archive & archive, const uint32_t version) private
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows serialisation.
operator<<
std::ostream& operator<< (std::ostream & os, const Forcefield & ff) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by Forcefield::GetAngleType(), Forcefield::GetAtomType(), Forcefield::GetBondType(), Forcefield::GetDihedralType(), Forcefield::GetFamily(), Forcefield::GetName(), Forcefield::NewAngleType(), Forcefield::NewAtomType(), Forcefield::NewBondType(), Forcefield::NewDihedralType(), Forcefield::NumAngleTypes(), Forcefield::NumAtomTypes(), Forcefield::NumBondTypes(), Forcefield::NumDihedralTypes(), Forcefield::ReserveAngleTypes(), Forcefield::ReserveAtomTypes(), Forcefield::ReserveBondTypes(), Forcefield::ReserveDihedralTypes(), and Forcefield::serialise().
The documentation for this class was generated from the following files:
include/indigox/classes/forcefield.hpp
src/classes/forcefield.cpp