indigoX: FFAngle Class Reference
FFAngle Class Reference
#include <indigox/classes/forcefield.hpp>
Classes
struct Impl
Public Types
enum Type
Enum for the different function types a angle term can have.
Public Member Functions
FFAngle ()=default
FFAngle (const FFAngle &)=default
FFAngle (FFAngle &&)=default
~ FFAngle ()=default
double GetForceConstant () const
Get the force constant.
Forcefield GetForcefield () const
int32_t GetID () const
Get the ID for this type.
double GetIdealAngle () const
Get the ideal angle (in degrees).
FFAngle GetLinkedType () const
Get the linked type for this type.
Type GetType () const
Get the potential energy function type.
operator bool () const
bool operator!= (const FFAngle &ang) const
bool operator< (const FFAngle &ang) const
bool operator<= (const FFAngle &ang) const
FFAngle & operator= (const FFAngle &)=default
FFAngle & operator= (FFAngle &&)=default
bool operator== (const FFAngle &ang) const
bool operator> (const FFAngle &ang) const
bool operator>= (const FFAngle &ang) const
Private Types
using AllowedMask = eastl::bitset< num_allow_positions, uint8_t >
Type used for storing allowed parameters.
enum AllowEnum
Enum giving the allow positions of each parameter type.
using DataStore = std::array< double, STORE_SIZE >
Type used to store all the internal data.
enum StoreEnum
Enum giving the stored index of each parameter type.
Private Member Functions
FFAngle (Type type, int32_t id, FFParam parameters, const Forcefield &ff)
Normal constructor.
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows serialisation.
class Forcefield
Friendship allows angle types to be added to a forcefield.
std::ostream & operator<< (std::ostream &os, const FFAngle &ang)
Member Typedef Documentation
AllowedMask
using AllowedMask = eastl::bitset<num_allow_positions, uint8_t> private
Type used for storing allowed parameters.
DataStore
using DataStore = std::array<double, STORE_SIZE> private
Type used to store all the internal data.
Member Enumeration Documentation
AllowEnum
enum AllowEnum private
Enum giving the allow positions of each parameter type.
Enumerator
Allow_ForceConstant
Allow_IdealAngle
num_allow_positions
StoreEnum
enum StoreEnum private
Enum giving the stored index of each parameter type.
Enumerator
Store_ForceConstant
Store_IdealAngle
STORE_SIZE
Type
enum Type strong
Enum for the different function types a angle term can have.
Though other values are provided, currently only the harmonic and cosine-harmonic function types are technically supported.
Enumerator
Empty
Harmonic
CosineHarmonic
UreyBradley
Quartic
Constructor & Destructor Documentation
FFAngle() [1/4]
FFAngle () default
FFAngle() [2/4]
FFAngle (const FFAngle &) default
FFAngle() [3/4]
FFAngle (FFAngle &&) default
~ FFAngle()
~ FFAngle () default
FFAngle() [4/4]
FFAngle (Type type, int32_t id, FFParam parameters, const Forcefield & ff) private
Normal constructor.
Creates a new angle of the specified type.
Parameters
type the type of the potential energy function to use.
id the ID of the type.
parameters the list of parameters for the function.
ff the forcefield this type will belong to.
Member Function Documentation
GetForceConstant()
double GetForceConstant () const
Get the force constant.
Returns
the force constant.
Exceptions
std::runtime_error if the type does not allow a force constant.
GetForcefield()
Forcefield GetForcefield () const
Referenced by Angle::SetType().
GetID()
int32_t GetID () const
Get the ID for this type.
Returns
the ID of this dihedral type.
Referenced by FFAngle::operator<(), indigox::operator<<(), FFAngle::operator==(), and FFAngle::operator>().
GetIdealAngle()
double GetIdealAngle () const
Get the ideal angle (in degrees).
Returns
the ideal angle.
Exceptions
std::runtime_error if the type does not allow an ideal angle.
GetLinkedType()
FFAngle GetLinkedType () const
Get the linked type for this type.
A linked type is an equivalent type with a different functional type.
Returns
the linked type.
Referenced by ParamAngle::MappedWith().
GetType()
AngleType GetType () const
Get the potential energy function type.
Returns
the type of the potential energy function.
Referenced by FFAngle::operator<(), indigox::operator<<(), FFAngle::operator==(), and FFAngle::operator>().
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const FFAngle & ang) const inline
operator<()
bool operator< (const FFAngle & ang) const
operator<=()
bool operator<= (const FFAngle & ang) const inline
operator=() [1/2]
FFAngle& operator= (const FFAngle &) default
operator=() [2/2]
FFAngle& operator= (FFAngle &&) default
operator==()
bool operator== (const FFAngle & ang) const
operator>()
bool operator> (const FFAngle & ang) const
operator>=()
bool operator>= (const FFAngle & ang) const inline
serialise()
void serialise (Archive & archive, const uint32_t version) private
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows serialisation.
Forcefield
friend class Forcefield friend
Friendship allows angle types to be added to a forcefield.
operator<<
std::ostream& operator<< (std::ostream & os, const FFAngle & ang) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by FFAngle::GetForceConstant(), FFAngle::GetForcefield(), FFAngle::GetID(), FFAngle::GetIdealAngle(), FFAngle::GetLinkedType(), FFAngle::GetType(), Forcefield::LinkAngleTypes(), FFAngle::operator==(), and FFAngle::serialise().
The documentation for this class was generated from the following files:
include/indigox/classes/forcefield.hpp
src/classes/forcefield.cpp