indigoX: FFBond Class Reference
FFBond Class Reference
#include <indigox/classes/forcefield.hpp>
Classes
struct Impl
Public Types
enum Type
Enum for the different function types a bond term can have.
Public Member Functions
FFBond ()=default
FFBond (const FFBond &)=default
FFBond (FFBond &&)=default
~ FFBond ()=default
double GetForceConstant () const
Get the force constant.
Forcefield GetForcefield () const
int32_t GetID () const
Get the ID for this type.
double GetIdealLength () const
Get the ideal angle (in degrees).
FFBond GetLinkedType () const
Get the linked type for this type.
Type GetType () const
Get the potential energy function type.
operator bool () const
bool operator!= (const FFBond &bnd) const
bool operator< (const FFBond &bnd) const
bool operator<= (const FFBond &bnd) const
FFBond & operator= (const FFBond &)=default
FFBond & operator= (FFBond &&)=default
bool operator== (const FFBond &bnd) const
bool operator> (const FFBond &bnd) const
bool operator>= (const FFBond &bnd) const
Private Types
using AllowedMask = eastl::bitset< num_allow_positions, uint8_t >
Type used for storing allowed parameters.
enum AllowEnum
Enum giving the allow positions of each parameter type.
using DataStore = std::array< double, STORE_SIZE >
Type used to store all the internal data.
enum StoreEnum
Enum giving the stored index of each parameter type.
Private Member Functions
FFBond (Type type, int32_t id, FFParam params, const Forcefield &ff)
Normal constructor.
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows serialisation.
class Forcefield
Friendship allows bond types to be added to a forcefield.
std::ostream & operator<< (std::ostream &os, const FFBond &bnd)
Member Typedef Documentation
AllowedMask
using AllowedMask = eastl::bitset<num_allow_positions, uint8_t> private
Type used for storing allowed parameters.
DataStore
using DataStore = std::array<double, STORE_SIZE> private
Type used to store all the internal data.
Member Enumeration Documentation
AllowEnum
enum AllowEnum private
Enum giving the allow positions of each parameter type.
Enumerator
Allow_ForceConstant
Allow_IdealLength
num_allow_positions
StoreEnum
enum StoreEnum private
Enum giving the stored index of each parameter type.
Enumerator
Store_ForceConstant
Store_IdealLength
STORE_SIZE
Type
enum Type strong
Enum for the different function types a bond term can have.
Though other values are provided, currently only the harmonic and quartic function types are technically supported.
Enumerator
Empty
An empty bond type with no parameters.
Harmonic
A harmonic bond type taking the form .
Quartic
A quartic bond type taking the form .
Morse
Cubic
FENE
Constructor & Destructor Documentation
FFBond() [1/4]
FFBond () default
FFBond() [2/4]
FFBond (const FFBond &) default
FFBond() [3/4]
FFBond (FFBond &&) default
~ FFBond()
~ FFBond () default
FFBond() [4/4]
FFBond (Type type, int32_t id, FFParam params, const Forcefield & ff) private
Normal constructor.
Creates a new bond of the specified type.
Parameters
type the type of the potential energy function to use.
id the ID of the type.
parameters the list of parameters for the function.
ff the forcefield this type will belong to.
Member Function Documentation
GetForceConstant()
double GetForceConstant () const
Get the force constant.
Returns
the force constant.
Exceptions
std::runtime_error if the type does not allow a force constant.
GetForcefield()
Forcefield GetForcefield () const
Referenced by Bond::SetType().
GetID()
int32_t GetID () const
Get the ID for this type.
Returns
the ID of this dihedral type.
Referenced by FFBond::operator<(), indigox::operator<<(), FFBond::operator==(), and FFBond::operator>().
GetIdealLength()
double GetIdealLength () const
Get the ideal angle (in degrees).
Returns
the ideal angle.
Exceptions
std::runtime_error if the type does not allow an ideal angle.
GetLinkedType()
FFBond GetLinkedType () const
Get the linked type for this type.
A linked type is an equivalent type with a different functional type.
Returns
the linked type.
Referenced by ParamBond::MappedWith().
GetType()
BondType GetType () const
Get the potential energy function type.
Returns
the type of the potential energy function.
Referenced by FFBond::operator<(), indigox::operator<<(), FFBond::operator==(), and FFBond::operator>().
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const FFBond & bnd) const inline
operator<()
bool operator< (const FFBond & bnd) const
operator<=()
bool operator<= (const FFBond & bnd) const inline
operator=() [1/2]
FFBond& operator= (const FFBond &) default
operator=() [2/2]
FFBond& operator= (FFBond &&) default
operator==()
bool operator== (const FFBond & bnd) const
operator>()
bool operator> (const FFBond & bnd) const
operator>=()
bool operator>= (const FFBond & bnd) const inline
serialise()
void serialise (Archive & archive, const uint32_t version) private
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows serialisation.
Forcefield
friend class Forcefield friend
Friendship allows bond types to be added to a forcefield.
operator<<
std::ostream& operator<< (std::ostream & os, const FFBond & bnd) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by FFBond::GetForcefield(), FFBond::GetID(), FFBond::GetIdealLength(), FFBond::GetLinkedType(), FFBond::GetType(), Forcefield::LinkBondTypes(), FFBond::operator==(), and FFBond::serialise().
The documentation for this class was generated from the following files:
include/indigox/classes/forcefield.hpp
src/classes/forcefield.cpp