indigoX: Bond Class Reference
Bond Class Reference
#include <indigox/classes/bond.hpp>
Classes
struct Impl
Public Types
using BondAtoms = std::array< Atom, 2 >
Container for storing Atom references assigned to an Bond.
enum Order
Enum for the different possible bond orders.
enum Stereo
Enum for the different possible bond stereochemistry states.
Public Member Functions
Bond ()=default
Bond (const Bond &)=default
Bond (Bond &&)=default
~ Bond ()=default
const BondAtoms & GetAtoms () const
Get the atoms of the bond.
int64_t GetID () const
int64_t GetIndex () const
Get the index from the molecule.
const Molecule & GetMolecule () const
Molecule this bond is associated with.
Order GetOrder () const
Get the bond order of the bond.
Stereo GetStereochemistry () const
Get the stereochemistry of the bond.
int64_t GetTag () const
Tag of the bond.
const FFBond & GetType () const
Get the type of the bond.
bool HasType () const
bool IsAmideBond () const
bool IsCarbonylBond () const
constexpr int64_t NumAtoms () const
Number of atoms this bond is between.
operator bool () const
bool operator!= (const Bond &bnd) const
bool operator< (const Bond &bnd) const
bool operator<= (const Bond &bnd) const
Bond & operator= (const Bond &)=default
Bond & operator= (Bond &&)=default
bool operator== (const Bond &bnd) const
bool operator> (const Bond &bnd) const
bool operator>= (const Bond &bnd) const
void SetOrder (Order order)
Set the bond order.
void SetStereochemistry (Stereo stereo)
Set the stereochemistry of the bond.
void SetTag (int64_t tag)
Set the tag of this bond.
void SetType (const FFBond &type)
Set the type of the bond.
Private Member Functions
Bond (const Atom &a, const Atom &b, const Molecule &m, Order o)
Normal constructor.
void Reset ()
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows serialisation.
class indigox::Molecule
Friendship allows IXMolecule to create new bonds.
std::ostream & operator<< (std::ostream &os, const Bond &bnd)
Member Typedef Documentation
BondAtoms
using BondAtoms = std::array<Atom, 2>
Container for storing Atom references assigned to an Bond.
Member Enumeration Documentation
Order
enum Order strong
Enum for the different possible bond orders.
Enumerator
UNDEFINED
No defined bond order.
SINGLE
Bond order of 1.
DOUBLE
Bond order of 2.
TRIPLE
Bond order of 3.
QUADRUPLE
Bond order of 4.
AROMATIC
Aromatic bond.
ONEANDAHALF
Non-aromatic bond order of 1.5.
TWOANDAHALF
Bond order of 2.5.
Stereo
enum Stereo strong
Enum for the different possible bond stereochemistry states.
Enumerator
UNDEFINED
No defined stereochemistry.
NONE
Defined as no stereochemistry.
E
E isomer.
Z
Z isomer.
Constructor & Destructor Documentation
Bond() [1/4]
Bond () default
Bond() [2/4]
Bond (const Bond &) default
Bond() [3/4]
Bond (Bond &&) default
~ Bond()
~ Bond () default
Bond() [4/4]
Bond (const Atom & a, const Atom & b, const Molecule & m, Order o) private
Normal constructor.
Creates a bond between the two atoms, linking it to the given Molecule.
Parameters
a,b the atoms to construct a bonds between.
m the molecule to assign the bond to.
Member Function Documentation
GetAtoms()
const Bond::BondAtoms & GetAtoms () const
Get the atoms of the bond.
Returns
pair of the atoms of the bond.
Referenced by MolecularGraph::AddEdge(), indigox::CanCutEdge(), CMGEdge::CMGEdge(), ParamMolecule::GetBond(), Bond::IsAmideBond(), Bond::IsCarbonylBond(), Molecule::PerceiveAngles(), Molecule::PerceiveDihedrals(), and Molecule::RemoveBond().
GetID()
int64_t GetID () const
Referenced by Molecule::GetBondID().
GetIndex()
int64_t GetIndex () const
Get the index from the molecule.
Calculates the index of the bond in the container of bonds of the molecule it is a part of. If the molecule is dead, the index returned is the tag of the bond.
Returns
the index of the bond.
Referenced by indigox::graph::operator<<().
GetMolecule()
const Molecule & GetMolecule () const
Molecule this bond is associated with.
The returned shared_ptr is empty if the bond is not assigned to a valid molecule.
Returns
the molecule associated with this bond.
Referenced by Molecule::HasBond().
GetOrder()
BondOrder GetOrder () const
Get the bond order of the bond.
Returns
the bond order.
Todo:
Obtain order based on molecule data.
Referenced by indigox::CanCutEdge(), CMGEdge::CMGEdge(), CMGVertex::CMGVertex(), and indigox::graph::Condense().
GetStereochemistry()
BondStereo GetStereochemistry () const
Get the stereochemistry of the bond.
Returns
the stereochemistry of the bond.
Todo:
Obtain stereochemistry based on molecule data.
Referenced by CMGEdge::CMGEdge().
GetTag()
int64_t GetTag () const
Tag of the bond.
This value may be modified without warning. Use with caution. For a constant identifier to the bond, use IXBond::GetUniqeID().
Returns
the tag assigned to the bond.
Referenced by Molecule::GetBondTag().
GetType()
const FFBond & GetType () const
Get the type of the bond.
Returns
the type of the bond.
Referenced by ParamBond::MappedWith().
HasType()
bool HasType () const
Referenced by ParamBond::MappedWith().
IsAmideBond()
bool IsAmideBond () const
IsCarbonylBond()
bool IsCarbonylBond () const
Referenced by Residue::Impl::AminoAcidTest().
NumAtoms()
constexpr int64_t NumAtoms () const inline
Number of atoms this bond is between.
Returns
2.
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const Bond & bnd) const inline
operator<()
bool operator< (const Bond & bnd) const
operator<=()
bool operator<= (const Bond & bnd) const inline
operator=() [1/2]
Bond& operator= (const Bond &) default
operator=() [2/2]
Bond& operator= (Bond &&) default
operator==()
bool operator== (const Bond & bnd) const
operator>()
bool operator> (const Bond & bnd) const
operator>=()
bool operator>= (const Bond & bnd) const inline
Reset()
void Reset () private
Referenced by Molecule::RemoveAtom(), and Molecule::RemoveBond().
serialise()
void serialise (Archive & archive, const uint32_t version) private
SetOrder()
void SetOrder (Order order)
Set the bond order.
Parameters
order the bond order to set.
Referenced by IXElectronAssigner::AssignAlgorithm::ApplyAssignment(), and Benzene().
SetStereochemistry()
void SetStereochemistry (Stereo stereo)
Set the stereochemistry of the bond.
Parameters
stereo the stereochemistry to set.
SetTag()
void SetTag (int64_t tag)
Set the tag of this bond.
The tag of a bond should not be considered stable. Use with caution.
Parameters
tag the tag to set.
SetType()
void SetType (const FFBond & type)
Set the type of the bond.
Parameters
type the type of bond to set.
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows serialisation.
indigox::Molecule
friend class indigox::Molecule friend
Friendship allows IXMolecule to create new bonds.
operator<<
std::ostream& operator<< (std::ostream & os, const Bond & bnd) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by Bond::GetAtoms(), Bond::GetID(), Bond::GetIndex(), Bond::GetMolecule(), Bond::GetOrder(), Bond::GetStereochemistry(), Bond::GetTag(), Bond::GetType(), Bond::HasType(), Molecule::NewBond(), Bond::operator<(), indigox::operator<<(), Bond::operator==(), Bond::operator>(), Molecule::RemoveAtom(), Bond::Reset(), Bond::serialise(), Bond::SetOrder(), Bond::SetStereochemistry(), Bond::SetTag(), and Bond::SetType().
The documentation for this class was generated from the following files:
include/indigox/classes/bond.hpp
src/classes/bond.cpp