indigoX: PeriodicTable Class Reference
PeriodicTable Class Reference
Singleton class for storing and access elemental information.
#include <indigox/classes/periodictable.hpp>
Public Member Functions
Element GetElement (const int32_t z) const
Get the element with the given atomic number.
Element GetElement (const std::string name) const
Get the element with the given name or symbol.
Element GetUndefined () const
Get the element for use when an element is not defined.
size_t NumElements () const
Number of elements in the PeriodicTable.
Element operator[] (const int32_t z) const
Get the element with the given atomic number.
Element operator[] (const std::string name) const
Get the element with the given name or symbol.
Private Member Functions
PeriodicTable ()
void GeneratePeriodicTable ()
Generate Elements.
Private Attributes
std::array< Element, 119 > _elems
Map atomic numbers to elements.
eastl::vector_map< std::string, size_t > _name_to_idx
Map symbol and name to vector index.
Friends
const PeriodicTable & GetPeriodicTable ()
Friendship allows for access to a single PeriodicTable instance.
struct indigox::test::TestPeriodicTable
Friendship allws for testing implementation.
Detailed Description
Singleton class for storing and access elemental information.
The IXPeriodicTable class provides the only means to access the IXElement class. Access to the instance should only be obtained using the GetInstance() method. Like most other classes in the indigoX library, usage is primarily intended through the use of smart pointers.
Constructor & Destructor Documentation
PeriodicTable()
PeriodicTable () private
Member Function Documentation
GeneratePeriodicTable()
void GeneratePeriodicTable () private
Generate Elements.
Currently, the first 118 elements are generated. These are hard coded into the implementation file. These are populated into both the _z_to and _name_to maps.
GetElement() [1/2]
Element GetElement (const int32_t z) const
Get the element with the given atomic number.
Parameters
z the atomic number of the element to get.
Returns
the requested element.
Exceptions
std::invalid_argument If the requested atomic number does not exist within the PeriodicTable.
Referenced by ElectronOpt::LoadScores(), and PeriodicTable::operator[]().
GetElement() [2/2]
Element GetElement (const std::string name) const
Get the element with the given name or symbol.
Name based matches are made ignoring case. Symbol matches are made checking case as well.
Parameters
name the name or symbol of the element to get.
Returns
the requested element.
Exceptions
std::invalid_argument If the requested name or symbol does not exist within the PeriodicTable.
GetUndefined()
Element GetUndefined () const inline
Get the element for use when an element is not defined.
As there is not much point in an undefined element, this method is intended for internal use.
Returns
the undefined Element.
Referenced by IXElectronAssigner::LoadScoreTable(), indigox::PeriodicTable_ToString(), and Atom::Reset().
NumElements()
size_t NumElements () const inline
Number of elements in the PeriodicTable.
Returns
the number of elements in the PeriodicTable.
Referenced by indigox::PeriodicTable_ToString().
operator[]() [1/2]
Element operator[] (const int32_t z) const inline
Get the element with the given atomic number.
Parameters
z the atomic number of the element to get.
Returns
the requested element.
See also
IXPeriodicTable::GetElement(const uint8_t) const
operator[]() [2/2]
Element operator[] (const std::string name) const inline
Get the element with the given name or symbol.
Parameters
name the name or symbol of the element to get.
Returns
the requested element.
See also
IXPeriodicTable::GetElement(const std::string) const
Friends And Related Function Documentation
GetPeriodicTable
const PeriodicTable& GetPeriodicTable () friend
Friendship allows for access to a single PeriodicTable instance.
indigox::test::TestPeriodicTable
friend struct indigox::test::TestPeriodicTable friend
Friendship allws for testing implementation.
Member Data Documentation
_elems
std::array<Element, 119 > _elems private
Map atomic numbers to elements.
Referenced by PeriodicTable::GeneratePeriodicTable(), PeriodicTable::GetElement(), PeriodicTable::GetUndefined(), and PeriodicTable::NumElements().
_name_to_idx
eastl::vector_map<std::string, size_t> _name_to_idx private
Map symbol and name to vector index.
Referenced by PeriodicTable::GeneratePeriodicTable(), and PeriodicTable::GetElement().
The documentation for this class was generated from the following files:
include/indigox/classes/periodictable.hpp
src/classes/periodictable.cpp