indigoX: MGEdge Class Reference
MGEdge Class Reference
Class for the edges of a IXMolecularGraph.
#include <indigox/graph/molecular.hpp>
Classes
struct MGEdgeData
Public Member Functions
MGEdge ()=default
MGEdge (const MGEdge &)=default
MGEdge (MGEdge &&)=default
~ MGEdge ()=default
const Bond & GetBond () const
Get the bond associated with this edge.
const MolecularGraph & GetGraph () const
Get the graph this edge is part of.
operator bool () const
bool operator!= (const MGEdge &e) const
bool operator< (const MGEdge &e) const
bool operator<= (const MGEdge &e) const
MGEdge & operator= (MGEdge &&)=default
MGEdge & operator= (const MGEdge &)=default
bool operator== (const MGEdge &e) const
bool operator> (const MGEdge &e) const
bool operator>= (const MGEdge &e) const
Private Member Functions
MGEdge (const Bond &b, const MolecularGraph &graph)
Construct an edge from a bond.
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< MGEdgeData > m_data
Friends
class cereal::access
Friendship allows for serialisation.
class MolecularGraph
Friendship allows IXMolecularGraph to add edges.
std::ostream & operator<< (std::ostream &os, const MGEdge &e)
Detailed Description
Class for the edges of a IXMolecularGraph.
Constructor & Destructor Documentation
MGEdge() [1/4]
MGEdge () default
MGEdge() [2/4]
MGEdge (const MGEdge &) default
MGEdge() [3/4]
MGEdge (MGEdge &&) default
~ MGEdge()
~ MGEdge () default
MGEdge() [4/4]
MGEdge (const Bond & b, const MolecularGraph & graph) private
Construct an edge from a bond.
Private constructor ensures that only IXMolecularGraph can create IXMGEdge instances.
Parameters
b the bond to associate with this edge.
Member Function Documentation
GetBond()
const Bond & GetBond () const
Get the bond associated with this edge.
Returns
the bond associated with this edge, if it is still alive.
Referenced by indigox::CanCutEdge(), CMGEdge::CMGEdge(), CMGVertex::CMGVertex(), indigox::graph::Condense(), indigox::graph::operator<<(), MolecularGraph::RemoveEdge(), and MolecularGraph::RemoveVertex().
GetGraph()
const MolecularGraph & GetGraph () const
Get the graph this edge is part of.
Returns
the owning graph.
Referenced by CondensedMolecularGraph::AddEdge().
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const MGEdge & e) const inline
operator<()
bool operator< (const MGEdge & e) const
operator<=()
bool operator<= (const MGEdge & e) const inline
operator=() [1/2]
MGEdge& operator= (MGEdge &&) default
operator=() [2/2]
MGEdge& operator= (const MGEdge &) default
operator==()
bool operator== (const MGEdge & e) const
operator>()
bool operator> (const MGEdge & e) const
operator>=()
bool operator>= (const MGEdge & e) const inline
serialise()
void serialise (Archive & archive, const uint32_t version) private
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows for serialisation.
MolecularGraph
friend class MolecularGraph friend
Friendship allows IXMolecularGraph to add edges.
operator<<
std::ostream& operator<< (std::ostream & os, const MGEdge & e) friend
Member Data Documentation
m_data
std::shared_ptr<MGEdgeData> m_data private
Referenced by MGEdge::GetBond(), MGEdge::GetGraph(), MGEdge::operator<(), MGEdge::operator==(), MGEdge::operator>(), and MGEdge::serialise().
The documentation for this class was generated from the following files:
include/indigox/graph/molecular.hpp
src/graph/molecular.cpp