indigoX: Molecule Class Reference
Molecule Class Reference
#include <indigox/classes/molecule.hpp>
Classes
struct Impl
Public Types
using MoleculeAngles = std::vector< Angle >
Container for storing IXAngle instances.
using MoleculeAtoms = std::vector< Atom >
Container for storing IXAtom instances.
using MoleculeBonds = std::vector< Bond >
Container for storing IXBond instances.
using MoleculeDihedrals = std::vector< Dihedral >
Container for storing IXDihedral instances.
using MoleculeResidues = std::vector< Residue >
Public Member Functions
Molecule (std::string name)
Default constructor.
Molecule ()=default
Molecule (Molecule &&)=default
Molecule (const Molecule &)=default
~ Molecule ()=default
Angle GetAngle (uint32_t pos)
Get the angle at position pos.
Angle GetAngle (const Atom &a, const Atom &b, const Atom &c)
Get the angle between three atoms, if it exists.
Angle GetAngleID (int64_t id) const
Get the angle with the given id.
const MoleculeAngles & GetAngles ()
Angle GetAngleTag (int64_t tag) const
Get the first angle with the given tag.
Atom GetAtom (uint32_t pos) const
Get the atom at position pos.
Atom GetAtomID (int64_t id) const
Get the atom with the given id.
const MoleculeAtoms & GetAtoms () const
Atom GetAtomTag (int64_t tag) const
Get the first atom with the given tag.
Bond GetBond (uint32_t pos) const
Get the bond at position pos.
Bond GetBond (const Atom &a, const Atom &b) const
Get the bond between two atoms, if it exists.
Bond GetBondID (int64_t id) const
Get the bond with the given id.
const MoleculeBonds & GetBonds () const
Bond GetBondTag (int64_t tag) const
Get the first bond with the given tag.
const graph::CondensedMolecularGraph & GetCondensedGraph () const
Dihedral GetDihedral (uint32_t pos)
Get the angle at position pos.
Dihedral GetDihedral (const Atom &a, const Atom &b, const Atom &c, const Atom &d)
Get the dihedral between four atoms, it if exists.
Dihedral GetDihedralID (int64_t id) const
Get the dihedral with the given id.
const MoleculeDihedrals & GetDihedrals ()
Dihedral GetDihedralTag (int64_t tag) const
Get the first dihedral with the given tag.
const Forcefield & GetForcefield () const
std::string GetFormula ()
Get the molecular formula of the molecule.
const graph::MolecularGraph & GetGraph () const
Get the molecular graph for this molecule.
int32_t GetMolecularCharge () const
Get the molecular charge of the molecule.
const std::string & GetName () const
Get the name of the molecule.
Residue GetResidueID (int32_t id)
const MoleculeResidues & GetResidues ()
bool HasAngle (const Angle &angle) const
Check if the angle is owned by this molecule.
bool HasAngle (const Atom &a, const Atom &b, const Atom &c)
Check if an angle between three atoms exists in this molecule.
bool HasAtom (const Atom &atom) const
Check if the atom is owned by this molecule.
bool HasBond (const Bond &bond) const
Check if the bond is owned by this molecule.
bool HasBond (const Atom &a, const Atom &b) const
Check if a bond between two atoms exists in this molecule.
bool HasDihedral (const Dihedral &dihedral) const
Check if the dihedral is owned by this molecule.
bool HasDihedral (const Atom &a, const Atom &b, const Atom &c, const Atom &d)
Check if a dihedral between four atoms exists in this molecule.
bool HasForcefield () const
void ModificationMade ()
Atom NewAtom ()
Create a new atom owned by the molecule.
Atom NewAtom (const Element &element)
Create a new atom of the given element for the molecule.
Atom NewAtom (const Element &element, double x, double y, double z)
Create a new named atom of the given element for the molecule.
Bond NewBond (const Atom &a, const Atom &b)
Create a bond between two atoms.
Dihedral NewDihedral (const Atom &a, const Atom &b, const Atom &c, const Atom &d)
Create a dihedral between four atoms.
int64_t NumAngles ()
Get the number of angles in the molecule.
int64_t NumAtoms () const
Get the number of atoms in the molecule.
int64_t NumBonds () const
Get the number of bonds in the molecule.
int64_t NumDihedrals ()
Get the number of dihedrals in the molecule.
operator bool () const
bool operator!= (const Molecule &mol) const
bool operator< (const Molecule &mol) const
bool operator<= (const Molecule &mol) const
Molecule & operator= (Molecule &&)=default
Molecule & operator= (const Molecule &)=default
bool operator== (const Molecule &mol) const
bool operator> (const Molecule &mol) const
bool operator>= (const Molecule &mol) const
void OptimiseChargeGroups ()
int64_t PerceiveAngles ()
Determine angles in the molecule.
int64_t PerceiveDihedrals ()
Determine dihedrals in the molecule.
int32_t PerceiveResidues ()
bool RemoveAtom (const Atom &atom)
Remove an atom from the molecule.
bool RemoveBond (const Bond &bond)
Remove a bond from the molecule.
bool RemoveBond (const Atom &a, const Atom &b)
Remove a bond between two atoms.
void ReorderAtoms (MoleculeAtoms &new_order)
void ReserveAtoms (int64_t num)
Reserve storage space for atoms.
void ReserveBonds (int64_t num)
Reserve storage space for bonds.
void ResetForcefield (const Forcefield &ff)
void SetForcefield (const Forcefield &ff)
void SetMolecularCharge (int32_t q)
Set the molecular charge of the molecule.
void SetName (std::string name)
Set the name of the molecule.
Private Member Functions
Angle NewAngle (const Atom &a, const Atom &b, const Atom &c)
Create an angle between three atoms.
Dihedral NewDihedral (const Atom &a, const Atom &b, const Atom &c, const Atom &d, bool manual)
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows serialisation.
std::ostream & operator<< (std::ostream &os, const Molecule &mol)
Member Typedef Documentation
MoleculeAngles
using MoleculeAngles = std::vector<Angle>
Container for storing IXAngle instances.
A molecule takes ownership of all angles it contains.
MoleculeAtoms
using MoleculeAtoms = std::vector<Atom>
Container for storing IXAtom instances.
A molecule takes ownership of all atoms it contains.
MoleculeBonds
using MoleculeBonds = std::vector<Bond>
Container for storing IXBond instances.
A molecule takes ownership of all bonds it contains.
MoleculeDihedrals
using MoleculeDihedrals = std::vector<Dihedral>
Container for storing IXDihedral instances.
A molecule takes ownership of all dihedrals it contains.
MoleculeResidues
using MoleculeResidues = std::vector<Residue>
Constructor & Destructor Documentation
Molecule() [1/4]
Molecule (std::string name)
Default constructor.
Is private to enforce that IXMolecules should only be used via the Molecule shared_ptr.
Molecule() [2/4]
Molecule () default
Molecule() [3/4]
Molecule (const Molecule &) default
Molecule() [4/4]
Molecule (Molecule &&) default
~ Molecule()
~ Molecule () default
Member Function Documentation
GetAngle() [1/2]
Angle GetAngle (uint32_t pos)
Get the angle at position pos.
Returns the angle at pos after a range check. If pos is not a valid index, returns an empty shared_ptr. Positioning of angles may change during normal operations. Angles are not re-percieved prior to retrieving the angle.
Parameters
pos the position of the angle to get.
Returns
the angle at pos or an empty shared_ptr.
Referenced by CherryPickerCallback::operator()().
GetAngle() [2/2]
Angle GetAngle (const Atom & a, const Atom & b, const Atom & c)
Get the angle between three atoms, if it exists.
Searches for an angle between the three atoms and returns it. If no angle is found, the returned shared_ptr is empty. Angles are re-perceived prior to searching.
Parameters
a,b,c the atoms to get the angle between. b is the central atom.
Returns
the angle between a and c centred on b.
GetAngleID()
Angle GetAngleID (int64_t id) const
Get the angle with the given id.
Returns the angle with the given unique id. If no such angle is found returns an empty shared_ptr. As the unique id of any created angles will be unknown, angles are not re-percieved prior to searching.
Parameters
id the unique id of the angle to retrieve.
Returns
the angle with the given id or an empty shared_ptr.
GetAngles()
const Molecule::MoleculeAngles & GetAngles ()
Referenced by Fragment::Fragment(), and ParamMolecule::ParamMoleculeImpl::ParamMoleculeImpl().
GetAngleTag()
Angle GetAngleTag (int64_t tag) const
Get the first angle with the given tag.
Returns the first angle with a tag matching that given. If no such angle is found, returns an empty shared_ptr. As tags are not set on creation of angles, angles are not re-percieved prior to searching.
Parameters
tag the angle tag to search for.
Returns
the first angle with the tag or an empty shared_ptr.
GetAtom()
Atom GetAtom (uint32_t pos) const
Get the atom at position pos.
Returns that atom at pos after a range check. If pos is not a valid index, returns an empty shared_ptr. Positioning of atoms may change during normal operations.
Parameters
pos the position of the atom to get.
Returns
the atom at pos or an empty shared_ptr.
GetAtomID()
Atom GetAtomID (int64_t id) const
Get the atom with the given id.
Returns the atom with the given unique id. If no such atom is found returns an empty shared_ptr.
Parameters
id the unique id of the atom to retrieve.
Returns
the atom with the given id or an empty shared_ptr.
GetAtoms()
const Molecule::MoleculeAtoms & GetAtoms () const
Referenced by ParamMolecule::ParamMoleculeImpl::ParamMoleculeImpl(), and Molecule::PerceiveDihedrals().
GetAtomTag()
Atom GetAtomTag (int64_t tag) const
Get the first atom with the given tag.
Returns the first atom with a tag matching that given. If no such atom is found, returns an empty shared_ptr.
Parameters
tag the atom tag to search for.
Returns
the first atom with the tag or an empty shared_ptr.
GetBond() [1/2]
Bond GetBond (uint32_t pos) const
Get the bond at position pos.
Returns that bond at pos after a range check. If pos is not a valid index, returns an empty shared_ptr. Positioning of bonds may change during normal operations.
Parameters
pos the position of the bond to get.
Returns
the bond at pos or an empty shared_ptr.
Referenced by CherryPickerCallback::operator()(), and Molecule::RemoveBond().
GetBond() [2/2]
Bond GetBond (const Atom & a, const Atom & b) const
Get the bond between two atoms, if it exists.
Searches for a bond between a and b and returns it. If no bond is found, returns an empty shared_ptr.
Parameters
a,b the atoms to get the bond between.
Returns
the bond between a and b or an empty shared_ptr.
GetBondID()
Bond GetBondID (int64_t id) const
Get the bond with the given id.
Returns the bond with the given unique id. If no such bond is found returns an empty shared_ptr.
Parameters
id the unique id of the bond to retrieve.
Returns
the bond with the given id or an empty shared_ptr.
GetBonds()
const Molecule::MoleculeBonds & GetBonds () const
Referenced by Fragment::Fragment(), and ParamMolecule::ParamMoleculeImpl::ParamMoleculeImpl().
GetBondTag()
Bond GetBondTag (int64_t tag) const
Get the first bond with the given tag.
Returns the first bond with a tag matching that given. If no such bond is found, returns an empty shared_ptr.
Parameters
tag the bond tag to search for.
Returns
the first bond with the tag or an empty shared_ptr.
GetCondensedGraph()
const graph::CondensedMolecularGraph & GetCondensedGraph () const
GetDihedral() [1/2]
Dihedral GetDihedral (uint32_t pos)
Get the angle at position pos.
Returns the dihedral at pos after a range check. If pos is not a valid index, returns an empty shared_ptr. Positioning of dihedrals may change during normal operations. Dihedrals are not re-perceived prior to retrieving the dihedral.
Parameters
pos the position of the dihedral to get.
Returns
the dihedral at pos or an empty shared_ptr.
Referenced by CherryPickerCallback::operator()().
GetDihedral() [2/2]
Dihedral GetDihedral (const Atom & a, const Atom & b, const Atom & c, const Atom & d)
Get the dihedral between four atoms, it if exists.
Searches for a dihedral between the four atoms and returns it. If no dihedral is found, the returned shared_ptr is empty. Dihedrals are re-perceived prior to searching.
Parameters
a,b,c,d the atoms to get the dihedral between.
Returns
the dihedral between a, b, c and d.
GetDihedralID()
Dihedral GetDihedralID (int64_t id) const
Get the dihedral with the given id.
Returns the dihedral with the given unique id. If no such dihedral is found returns an empty shared_ptr. As the unique id of any created dihedrals will be unknown, dihedrals are not re-perceived prior to searching.
Parameters
id the unique id of the dihedral to retrieve.
Returns
the dihedral with the given id or an empty shared_ptr.
GetDihedrals()
const Molecule::MoleculeDihedrals & GetDihedrals ()
Referenced by Fragment::Fragment(), and ParamMolecule::ParamMoleculeImpl::ParamMoleculeImpl().
GetDihedralTag()
Dihedral GetDihedralTag (int64_t tag) const
Get the first dihedral with the given tag.
Returns the first dihedral with a tag matching that given. If no such dihedral is found, returns an empty shared_ptr. As tags are not set on creation of dihedrals, dihedrals are not re-perceived prior to searching.
Parameters
tag the dihedral tag to search for.
Returns
the first dihedral with the tag or an empty shraed_ptr.
GetForcefield()
const Forcefield & GetForcefield () const
Referenced by Athenaeum::AddAllFragments(), and Athenaeum::AddFragment().
GetFormula()
std::string GetFormula ()
Get the molecular formula of the molecule.
Determines the molecular formula of the molecule. The elements of the formula are arranged in the order: carbon, hydrogen and then alphabetically by atomic symbol. The resultant formula is cached and recalculated only when the IXMolecule::ATOM_ELEMENTS property has been modified.
Returns
the molecular formula of the molecule.
GetGraph()
const graph::MolecularGraph & GetGraph () const
Get the molecular graph for this molecule.
Returns
the molecular graph of this molecule.
Referenced by Athenaeum::AddAllFragments(), Athenaeum::AddFragment(), Fragment::Fragment(), Residue::Impl::Impl(), IXElectronAssigner::AssignAlgorithm::Initalise(), and CherryPicker::ParameteriseMolecule().
GetMolecularCharge()
int32_t GetMolecularCharge () const
Get the molecular charge of the molecule.
Returns
the molecular charge of the molecule.
Referenced by IXElectronAssigner::AssignAlgorithm::Initalise().
GetName()
const std::string & GetName () const
Get the name of the molecule.
Returns
the name of the molecule.
GetResidueID()
Residue GetResidueID (int32_t id)
GetResidues()
const Molecule::MoleculeResidues & GetResidues ()
Referenced by Molecule::GetResidueID().
HasAngle() [1/2]
bool HasAngle (const Angle & angle) const
Check if the angle is owned by this molecule.
Parameters
angle the angle to check for.
Returns
if the angle is owned by this molecule.
HasAngle() [2/2]
bool HasAngle (const Atom & a, const Atom & b, const Atom & c)
Check if an angle between three atoms exists in this molecule.
If the Emergent::ANGLE_PERCEPTION property is set, angles are re-percieved prior to check for the existance of the angle. b is the central atom of the angle.
Parameters
a,b,c the atoms the angle should be between.
Returns
if there is an angle between the three atoms.
HasAtom()
bool HasAtom (const Atom & atom) const
Check if the atom is owned by this molecule.
Parameters
atom the atom to check for.
Returns
if the atom is owned by this molecule.
Referenced by Molecule::GetAngle(), Molecule::GetBond(), Molecule::GetDihedral(), Molecule::HasAngle(), Molecule::HasBond(), Molecule::HasDihedral(), Molecule::NewBond(), Molecule::NewDihedral(), Molecule::RemoveAtom(), and Molecule::ReorderAtoms().
HasBond() [1/2]
bool HasBond (const Bond & bond) const
Check if the bond is owned by this molecule.
Parameters
bond the bond to check for.
Returns
if the bond is owned by this molecule.
Referenced by Molecule::RemoveBond().
HasBond() [2/2]
bool HasBond (const Atom & a, const Atom & b) const
Check if a bond between two atoms exists in this molecule.
Parameters
a,b the atoms the bond should be between.
Returns
if there is a bond between the two atoms.
HasDihedral() [1/2]
bool HasDihedral (const Dihedral & dihedral) const
Check if the dihedral is owned by this molecule.
Parameters
dihedral the dihedral to check for.
Returns
if the dihedral is owned by this molecule.
HasDihedral() [2/2]
bool HasDihedral (const Atom & a, const Atom & b, const Atom & c, const Atom & d)
Check if a dihedral between four atoms exists in this molecule.
If the Emergent::DIHEDRAL_PERCEPTION property is set, dihedrals are re-perceived prior to checking for the existance of the dihedral.
Parameters
a,b,c,d the atoms the dihedral should be between.
Returns
if there is a dihedral between the four atoms.
HasForcefield()
bool HasForcefield () const
Referenced by Athenaeum::AddAllFragments(), Athenaeum::AddFragment(), and Molecule::SetForcefield().
ModificationMade()
void ModificationMade ()
NewAngle()
Angle NewAngle (const Atom & a, const Atom & b, const Atom & c) private
Create an angle between three atoms.
Parameters
a,b,c the atoms to create the angle between.
Returns
the new angle.
Referenced by Molecule::PerceiveAngles().
NewAtom() [1/3]
Atom NewAtom ()
Create a new atom owned by the molecule.
Returns
the new atom.
Referenced by Benzene(), Molecule::NewAtom(), and ProtonatedLysine().
NewAtom() [2/3]
Atom NewAtom (const Element & element)
Create a new atom of the given element for the molecule.
Parameters
element the element of the new atom.
Returns
the new atom.
NewAtom() [3/3]
Atom NewAtom (const Element & element, double x, double y, double z)
Create a new named atom of the given element for the molecule.
Parameters
name the name of the new atom.
element the element of the new atom.
Returns
the new atom.
NewBond()
Bond NewBond (const Atom & a, const Atom & b)
Create a bond between two atoms.
To create a bond, both atoms need to be owned by the molecule and there cannot be an existing bond between the atoms. If either condition is not met, the returned shared_ptr is empty.
Parameters
a,b the atoms to create a bond between.
Returns
the new bond.
Referenced by Benzene(), and ProtonatedLysine().
NewDihedral() [1/2]
Dihedral NewDihedral (const Atom & a, const Atom & b, const Atom & c, const Atom & d, bool manual) private
Referenced by Molecule::NewDihedral(), and Molecule::PerceiveDihedrals().
NewDihedral() [2/2]
Dihedral NewDihedral (const Atom & a, const Atom & b, const Atom & c, const Atom & d)
Create a dihedral between four atoms.
Parameters
a,b,c,d the atoms to create the dihedral between.
Returns
the new dihedral.
NumAngles()
int64_t NumAngles ()
Get the number of angles in the molecule.
If the Emergent::ANGLE_PERCEPTION property is set, angles are re-calculated prior to determining how many there are in the molecule.
Returns
the number of angles in the molecule.
Referenced by Molecule::GetAngle().
NumAtoms()
int64_t NumAtoms () const
Get the number of atoms in the molecule.
Returns
the number of atoms in the molecule.
Referenced by Athenaeum::AddAllFragments(), and Molecule::GetAtom().
NumBonds()
int64_t NumBonds () const
Get the number of bonds in the molecule.
Returns
the number of bonds in the molecule.
Referenced by Molecule::GetBond().
NumDihedrals()
int64_t NumDihedrals ()
Get the number of dihedrals in the molecule.
If the CONNECTIVITY property has been modified, dihedrals are re-calculated prior to determining how many there are in the molecule.
Returns
the number of dihedrals in the molecule.
Referenced by Molecule::GetDihedral().
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const Molecule & mol) const inline
operator<()
bool operator< (const Molecule & mol) const
operator<=()
bool operator<= (const Molecule & mol) const inline
operator=() [1/2]
Molecule& operator= (const Molecule &) default
operator=() [2/2]
Molecule& operator= (Molecule &&) default
operator==()
bool operator== (const Molecule & mol) const
operator>()
bool operator> (const Molecule & mol) const
operator>=()
bool operator>= (const Molecule & mol) const inline
OptimiseChargeGroups()
void OptimiseChargeGroups ()
PerceiveAngles()
int64_t PerceiveAngles ()
Determine angles in the molecule.
An angle is defined for each group of three connected atoms within a molecule. Subsequent calls to this method will only generate angles which have not been previously generated. Additionally, angles can only be removed by removing an atom or a bond.
Returns
the number of angles added.
Referenced by Molecule::GetAngle(), Molecule::GetAngles(), Molecule::HasAngle(), Molecule::NumAngles(), and CherryPicker::ParameteriseMolecule().
PerceiveDihedrals()
int64_t PerceiveDihedrals ()
Determine dihedrals in the molecule.
A dihedral is defined for each group of four connected atoms within a molecule. Subsequent calls to this method will only generate dihedrals which have not been previously generated. Additionally, dihedrals can only be removed by removing an atom or bond.
Returns
the number of dihedrals added.
Referenced by Molecule::GetDihedral(), Molecule::GetDihedrals(), Molecule::HasDihedral(), Molecule::NumDihedrals(), and CherryPicker::ParameteriseMolecule().
PerceiveResidues()
int32_t PerceiveResidues ()
Referenced by Molecule::GetResidues(), and main().
RemoveAtom()
bool RemoveAtom (const Atom & atom)
Remove an atom from the molecule.
In addition to removing the atom, any bonds to the atom are also removed. A removal will not occur if the atom is not owned by the molecule it is being removed from.
Parameters
atom the atom to remove.
Returns
if a removal occured.
RemoveBond() [1/2]
bool RemoveBond (const Bond & bond)
Remove a bond from the molecule.
A removal will not occur if the bond is not owned by the molecule it is being removed from. Reference to the bond is removed from both of the atoms of the bond.
Parameters
bond the bond to remove.
Returns
if a removal occured.
Referenced by Molecule::RemoveBond().
RemoveBond() [2/2]
bool RemoveBond (const Atom & a, const Atom & b)
Remove a bond between two atoms.
Parameters
a,b the atoms to remove a bond between.
Returns
if removal occured.
ReorderAtoms()
void ReorderAtoms (MoleculeAtoms & new_order)
Referenced by Molecule::OptimiseChargeGroups(), and Molecule::PerceiveResidues().
ReserveAtoms()
void ReserveAtoms (int64_t num)
Reserve storage space for atoms.
Reserves storage space for a minimum of num IXAtom instances. This is more efficient when building large molecules as the vector will not need to grow as more atoms are added.
Parameters
num the number of IXAtoms to reserve space for.
ReserveBonds()
void ReserveBonds (int64_t num)
Reserve storage space for bonds.
Reserves storage space for a minimum of num IXBond instances. This is more efficient when building large molecules as the vector will not need to grow as more bonds are added.
Parameters
num the number of IXBonds to reserve space for.
ResetForcefield()
void ResetForcefield (const Forcefield & ff)
serialise()
void serialise (Archive & archive, const uint32_t version) private
SetForcefield()
void SetForcefield (const Forcefield & ff)
SetMolecularCharge()
void SetMolecularCharge (int32_t q)
Set the molecular charge of the molecule.
Sets the IXMolecule::ELECTRON_COUNT property as modified.
Parameters
q the new charge to set.
SetName()
void SetName (std::string name)
Set the name of the molecule.
Parameters
name the new to set.
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows serialisation.
operator<<
std::ostream& operator<< (std::ostream & os, const Molecule & mol) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by Molecule::GetAngle(), Molecule::GetAngleID(), Molecule::GetAngles(), Molecule::GetAngleTag(), Molecule::GetAtom(), Molecule::GetAtomID(), Molecule::GetAtoms(), Molecule::GetAtomTag(), Molecule::GetBond(), Molecule::GetBondID(), Molecule::GetBonds(), Molecule::GetBondTag(), Molecule::GetCondensedGraph(), Molecule::GetDihedral(), Molecule::GetDihedralID(), Molecule::GetDihedrals(), Molecule::GetDihedralTag(), Molecule::GetForcefield(), Molecule::GetFormula(), Molecule::GetGraph(), Molecule::GetMolecularCharge(), Molecule::GetName(), Molecule::GetResidues(), Molecule::HasAngle(), Molecule::HasBond(), Molecule::HasDihedral(), Molecule::HasForcefield(), Molecule::ModificationMade(), Molecule::Molecule(), Molecule::NewAngle(), Molecule::NewAtom(), Molecule::NewBond(), Molecule::NewDihedral(), Molecule::NumAngles(), Molecule::NumAtoms(), Molecule::NumBonds(), Molecule::NumDihedrals(), Molecule::operator<(), Molecule::operator==(), Molecule::operator>(), Molecule::PerceiveAngles(), Molecule::PerceiveDihedrals(), Molecule::PerceiveResidues(), Molecule::RemoveAtom(), Molecule::RemoveBond(), Molecule::ReorderAtoms(), Molecule::ReserveAtoms(), Molecule::ReserveBonds(), Molecule::ResetForcefield(), Molecule::serialise(), Molecule::SetForcefield(), Molecule::SetMolecularCharge(), and Molecule::SetName().
The documentation for this class was generated from the following files:
include/indigox/classes/molecule.hpp
src/classes/molecule.cpp