indigoX: Residue Class Reference
Residue Class Reference
#include <indigox/classes/residue.hpp>
Classes
struct Impl
Public Types
using ResidueAtoms = eastl::vector_set< Atom >
enum Type
Public Member Functions
Residue ()=default
Residue (const Residue &)=default
Residue (Residue &&)=default
~ Residue ()=default
const ResidueAtoms & GetAtoms () const
Type GetType ()
Determine the type of the residue.
bool HasAtom (const Atom &atom) const
bool IsAlphaAminoAcid ()
bool IsAminoAcid ()
Determine if the residue is an amino acid.
bool IsBetaAminoAcid ()
bool IsDeltaAminoAcid ()
bool IsGammaAminoAcid ()
bool IsLipid ()
bool IsNucleicAcid ()
bool IsSugar ()
operator bool () const
bool operator!= (const Residue &res) const
bool operator< (const Residue &res) const
bool operator<= (const Residue &res) const
Residue & operator= (const Residue &)=default
Residue & operator= (Residue &&)=default
bool operator== (const Residue &res) const
bool operator> (const Residue &res) const
bool operator>= (const Residue &res) const
Private Member Functions
Residue (const std::vector< Atom > &atoms, const Molecule &mol)
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
class Molecule
std::ostream & operator<< (std::ostream &os, const Residue &res)
Member Typedef Documentation
ResidueAtoms
using ResidueAtoms = eastl::vector_set<Atom>
Member Enumeration Documentation
Type
enum Type strong
Enumerator
Unspecified
AminoAcid
NucleicAcid
Sugar
Lipid
NonSpecific
Constructor & Destructor Documentation
Residue() [1/4]
Residue (const std::vector< Atom > & atoms, const Molecule & mol) private
Residue() [2/4]
Residue () default
Residue() [3/4]
Residue (const Residue &) default
Residue() [4/4]
Residue (Residue &&) default
~ Residue()
~ Residue () default
Member Function Documentation
GetAtoms()
const Residue::ResidueAtoms & GetAtoms () const
GetType()
ResidueType GetType ()
Determine the type of the residue.
Checks if the residue matches each of the specific residue types, in order. The first type which matches is the returned type. If you want to check if a residue is also another type, use the IsType methods directly.
Referenced by Residue::IsLipid(), Residue::IsNucleicAcid(), Residue::IsSugar(), and Molecule::PerceiveResidues().
HasAtom()
bool HasAtom (const Atom & atom) const
IsAlphaAminoAcid()
bool IsAlphaAminoAcid ()
IsAminoAcid()
bool IsAminoAcid ()
Determine if the residue is an amino acid.
The algorithm for determining if a residue is an amino acid is as follows. First, all potential carboxylic acid and amine atoms are identified. For carbon atoms, they are classed as potential carboxylic acid atoms if they are 3 co-ordinate, have a carbonyl bond and another neighbouring oxygen atom. The additional neighbouring oxygen atom can also be accounted for by a bond between this residue and the next. For nitrogen atoms, they are classed as potential amine atoms if they have a hydrogen bond or a bond to the next residue. This allows for proline to be identified as an amino acid even though it technically is not.
Once all potential carboxylic and amine atoms are identified, shortest paths between all pairs of them are checked. If one of these paths consists of only carbon atoms, the residue is regarded as being an amino acid.
Referenced by Residue::IsAlphaAminoAcid(), Residue::IsBetaAminoAcid(), Residue::IsDeltaAminoAcid(), and Residue::IsGammaAminoAcid().
IsBetaAminoAcid()
bool IsBetaAminoAcid ()
IsDeltaAminoAcid()
bool IsDeltaAminoAcid ()
IsGammaAminoAcid()
bool IsGammaAminoAcid ()
IsLipid()
bool IsLipid ()
IsNucleicAcid()
bool IsNucleicAcid ()
IsSugar()
bool IsSugar ()
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const Residue & res) const inline
operator<()
bool operator< (const Residue & res) const
operator<=()
bool operator<= (const Residue & res) const inline
operator=() [1/2]
Residue& operator= (const Residue &) default
operator=() [2/2]
Residue& operator= (Residue &&) default
operator==()
bool operator== (const Residue & res) const
operator>()
bool operator> (const Residue & res) const
operator>=()
bool operator>= (const Residue & res) const inline
serialise()
void serialise (Archive & archive, const uint32_t version) private
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Molecule
friend class Molecule friend
operator<<
std::ostream& operator<< (std::ostream & os, const Residue & res) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by Residue::GetAtoms(), Residue::GetType(), Residue::HasAtom(), Residue::IsAlphaAminoAcid(), Residue::IsAminoAcid(), Residue::IsBetaAminoAcid(), Residue::IsDeltaAminoAcid(), Residue::IsGammaAminoAcid(), and Residue::serialise().
The documentation for this class was generated from the following files:
include/indigox/classes/residue.hpp
src/classes/residue.cpp