indigoX: ParamMolecule Class Reference
ParamMolecule Class Reference
#include <indigox/classes/parameterised.hpp>
Classes
struct ParamMoleculeImpl
Public Types
using PAngle = stdx::triple< Atom >
Type defining angles.
using ParamAngles = eastl::vector_map< PAngle, uint32_t >
Container type to hold parameterised angles.
using ParamAtoms = eastl::vector_map< Atom, uint32_t >
Container type to hold parameterised atoms.
using ParamBonds = eastl::vector_map< PBond, uint32_t >
Container type to hold parameterised bonds.
using ParamDihedrals = eastl::vector_map< PDihedral, uint32_t >
Container type to hold parameterised dihedrals.
using PBond = std::pair< Atom, Atom >
Type defining bonds.
using PDihedral = stdx::quad< Atom >
Type defining dihedrals.
Public Member Functions
ParamMolecule ()=default
ParamMolecule (const ParamMolecule &)=default
ParamMolecule (ParamMolecule &&)=default
ParamMolecule (const Molecule &mol)
Normal constructor.
~ ParamMolecule ()=default
void ApplyParameteristion (bool self_consistent)
Applies the current parameterisation state.
const ParamAngle & GetAngle (const Angle &ang) const
Get the parameterisation of an angle.
const ParamAngle & GetAngle (const Atom &a, const Atom &b, const Atom &c) const
Get the parameterisation of an angle.
const std::vector< ParamAngle > & GetAngles () const
const ParamAtom & GetAtom (const Atom &atm) const
Get the parameterisation of an atom.
const std::vector< ParamAtom > & GetAtoms () const
const ParamBond & GetBond (const Bond &bnd) const
Get the parameterisation of a bond.
const ParamBond & GetBond (const Atom &a, const Atom &b) const
Get the parameterisation of a bond.
const std::vector< ParamBond > & GetBonds () const
const ParamDihedral & GetDihedral (const Dihedral &dhd)
Get the parameterisation of a dihedral.
const ParamDihedral & GetDihedral (const Atom &a, const Atom &b, const Atom &c, const Atom &d)
Get the parameterisation of a dihedral.
const std::vector< ParamDihedral > & GetDihedrals () const
operator bool () const
bool operator!= (const ParamMolecule &mol) const
bool operator< (const ParamMolecule &mol) const
bool operator<= (const ParamMolecule &mol) const
ParamMolecule & operator= (const ParamMolecule &)=default
ParamMolecule & operator= (ParamMolecule &&)=default
bool operator== (const ParamMolecule &mol) const
bool operator> (const ParamMolecule &mol) const
bool operator>= (const ParamMolecule &mol) const
Private Attributes
std::shared_ptr< ParamMoleculeImpl > m_data
Friends
std::ostream & operator<< (std::ostream &os, const ParamMolecule &mol)
Member Typedef Documentation
PAngle
using PAngle = stdx::triple<Atom>
Type defining angles.
ParamAngles
using ParamAngles = eastl::vector_map<PAngle, uint32_t>
Container type to hold parameterised angles.
ParamAtoms
using ParamAtoms = eastl::vector_map<Atom, uint32_t>
Container type to hold parameterised atoms.
ParamBonds
using ParamBonds = eastl::vector_map<PBond, uint32_t>
Container type to hold parameterised bonds.
ParamDihedrals
using ParamDihedrals = eastl::vector_map<PDihedral, uint32_t>
Container type to hold parameterised dihedrals.
PBond
using PBond = std::pair<Atom, Atom>
Type defining bonds.
PDihedral
using PDihedral = stdx::quad<Atom>
Type defining dihedrals.
Constructor & Destructor Documentation
ParamMolecule() [1/4]
ParamMolecule () default
ParamMolecule() [2/4]
ParamMolecule (const ParamMolecule &) default
ParamMolecule() [3/4]
ParamMolecule (ParamMolecule &&) default
~ ParamMolecule()
~ ParamMolecule () default
ParamMolecule() [4/4]
ParamMolecule (const Molecule & mol)
Normal constructor.
Parameters
mol the molecule to parameterise.
Member Function Documentation
ApplyParameteristion()
void ApplyParameteristion (bool self_consistent)
Applies the current parameterisation state.
Goes through all parameterised parts and calls the apply parameterisation method on each of them.
Parameters
self_consistent apply parapmeterisation self consistently.
Referenced by CherryPicker::ParameteriseMolecule().
GetAngle() [1/2]
const ParamAngle & GetAngle (const Angle & ang) const
Get the parameterisation of an angle.
Parameters
ang the angle to get.
Returns
the parameterisation angle.
Referenced by CherryPickerCallback::operator()().
GetAngle() [2/2]
const ParamAngle & GetAngle (const Atom & a, const Atom & b, const Atom & c) const
Get the parameterisation of an angle.
Parameters
atms the triple of atoms the angle is between.
Returns
the parameterisation angle.
GetAngles()
const std::vector< ParamAngle > & GetAngles () const
GetAtom()
const ParamAtom & GetAtom (const Atom & atm) const
Get the parameterisation of an atom.
Parameters
atm the atom to get
Returns
the parameterisation atom.
Referenced by CherryPickerCallback::operator()().
GetAtoms()
const std::vector< ParamAtom > & GetAtoms () const
GetBond() [1/2]
const ParamBond & GetBond (const Bond & bnd) const
Get the parameterisation of a bond.
Parameters
bnd the bond to get
Returns
the parameterisation bond.
Referenced by CherryPickerCallback::operator()().
GetBond() [2/2]
const ParamBond & GetBond (const Atom & a, const Atom & b) const
Get the parameterisation of a bond.
Parameters
atms the pair of atoms the bond is between
Returns
the parameterisation bond.
GetBonds()
const std::vector< ParamBond > & GetBonds () const
GetDihedral() [1/2]
const ParamDihedral & GetDihedral (const Dihedral & dhd)
Get the parameterisation of a dihedral.
Parameters
dhd the dihedral to get.
Returns
the parameterisation dihedral.
Referenced by CherryPickerCallback::operator()().
GetDihedral() [2/2]
const ParamDihedral & GetDihedral (const Atom & a, const Atom & b, const Atom & c, const Atom & d)
Get the parameterisation of a dihedral.
To allow for the parameterisation of dihedrals, such as impropers used to keep chirality, which are not percieved within the molecule, if the given atoms are not found, a new ParamDihedral will be created.
Parameters
atms the quad of atoms the dihedral is between.
Returns
the parameterisation dihedral.
GetDihedrals()
const std::vector< ParamDihedral > & GetDihedrals () const
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const ParamMolecule & mol) const inline
operator<()
bool operator< (const ParamMolecule & mol) const
operator<=()
bool operator<= (const ParamMolecule & mol) const inline
operator=() [1/2]
ParamMolecule& operator= (ParamMolecule &&) default
operator=() [2/2]
ParamMolecule& operator= (const ParamMolecule &) default
operator==()
bool operator== (const ParamMolecule & mol) const
operator>()
bool operator> (const ParamMolecule & mol) const
operator>=()
bool operator>= (const ParamMolecule & mol) const inline
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ParamMolecule & mol) friend
Member Data Documentation
m_data
std::shared_ptr<ParamMoleculeImpl> m_data private
Referenced by ParamMolecule::ApplyParameteristion(), ParamMolecule::GetAngle(), ParamMolecule::GetAngles(), ParamMolecule::GetAtom(), ParamMolecule::GetAtoms(), ParamMolecule::GetBond(), ParamMolecule::GetBonds(), ParamMolecule::GetDihedral(), and ParamMolecule::GetDihedrals().
The documentation for this class was generated from the following files:
include/indigox/classes/parameterised.hpp
src/classes/parameterised.cpp