indigoX: FFAtom Class Reference
FFAtom Class Reference
#include <indigox/classes/forcefield.hpp>
Classes
struct Impl
Public Member Functions
FFAtom ()=default
FFAtom (const FFAtom &)=default
FFAtom (FFAtom &&)=default
~ FFAtom ()=default
Element GetElement () const
Forcefield GetForcefield () const
int32_t GetID () const
Get the ID for this type.
std::string GetName () const
Get the name for this type.
operator bool () const
bool operator!= (const FFAtom &atm) const
bool operator< (const FFAtom &atm) const
bool operator<= (const FFAtom &atm) const
FFAtom & operator= (const FFAtom &)=default
FFAtom & operator= (FFAtom &&)=default
bool operator== (const FFAtom &atm) const
bool operator> (const FFAtom &atm) const
bool operator>= (const FFAtom &atm) const
Private Member Functions
FFAtom (int32_t id, std::string name, const Element &element, const Forcefield &ff)
Normal constructor.
template<typename Archive >
void serialise (Archive &archive, const uint32_t version)
Private Attributes
std::shared_ptr< Impl > m_data
Friends
class cereal::access
Friendship allows serialisation.
class Forcefield
Friendship allows atom types to be added to a forcefield.
std::ostream & operator<< (std::ostream &os, const FFAtom &atm)
Constructor & Destructor Documentation
FFAtom() [1/4]
FFAtom () default
FFAtom() [2/4]
FFAtom (const FFAtom &) default
FFAtom() [3/4]
FFAtom (FFAtom &&) default
~ FFAtom()
~ FFAtom () default
FFAtom() [4/4]
FFAtom (int32_t id, std::string name, const Element & element, const Forcefield & ff) private
Normal constructor.
Creates a new atom term.
Parameters
id the ID of the type.
name the name of the atom type.
ff the forcefield this type will be a part of.
Member Function Documentation
GetElement()
Element GetElement () const
GetForcefield()
Forcefield GetForcefield () const
Referenced by Atom::SetType().
GetID()
int32_t GetID () const
Get the ID for this type.
Returns
the ID of this atom type.
Referenced by FFAtom::operator<(), indigox::operator<<(), FFAtom::operator==(), and FFAtom::operator>().
GetName()
std::string GetName () const
Get the name for this type.
Returns
the name of this atom type.
Referenced by FFAtom::operator==().
operator bool()
operator bool () const inline
operator!=()
bool operator!= (const FFAtom & atm) const inline
operator<()
bool operator< (const FFAtom & atm) const
operator<=()
bool operator<= (const FFAtom & atm) const inline
operator=() [1/2]
FFAtom& operator= (const FFAtom &) default
operator=() [2/2]
FFAtom& operator= (FFAtom &&) default
operator==()
bool operator== (const FFAtom & atm) const
operator>()
bool operator> (const FFAtom & atm) const
operator>=()
bool operator>= (const FFAtom & atm) const inline
serialise()
void serialise (Archive & archive, const uint32_t version) private
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Friendship allows serialisation.
Forcefield
friend class Forcefield friend
Friendship allows atom types to be added to a forcefield.
operator<<
std::ostream& operator<< (std::ostream & os, const FFAtom & atm) friend
Member Data Documentation
m_data
std::shared_ptr<Impl> m_data private
Referenced by FFAtom::GetElement(), FFAtom::GetForcefield(), FFAtom::GetID(), FFAtom::GetName(), and FFAtom::serialise().
The documentation for this class was generated from the following files:
include/indigox/classes/forcefield.hpp
src/classes/forcefield.cpp