indigoX: include/indigox/python/interface.hpp File Reference
interface.hpp File Reference
#include <pybind11/eigen.h>
#include <pybind11/operators.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <sstream>
#include "../utils/fwd_declares.hpp"
#include "opaquecontainers.hpp"
Functions
void GenerateOpaqueContainers (pybind11::module &m)
void GeneratePyAthenaeum (pybind11::module &m)
void GeneratePyElectronAssigner (pybind11::module &m)
void GeneratePyForcefield (pybind11::module &m)
void GeneratePyGraphAlgorithms (pybind11::module &m)
void GeneratePyGraphs (pybind11::module &m)
void GeneratePyMolecule (pybind11::module &m)
void GeneratePyParameterisedMolecule (pybind11::module &m)
void GeneratePyPeriodicTable (pybind11::module &m)
template<typename T >
std::string outstream_operator (const T &t)
Function Documentation
GenerateOpaqueContainers()
void GenerateOpaqueContainers (pybind11::module & m)
GeneratePyAthenaeum()
void GeneratePyAthenaeum (pybind11::module & m)
Referenced by PYBIND11_MODULE().
GeneratePyElectronAssigner()
void GeneratePyElectronAssigner (pybind11::module & m)
GeneratePyForcefield()
void GeneratePyForcefield (pybind11::module & m)
Referenced by PYBIND11_MODULE().
GeneratePyGraphAlgorithms()
void GeneratePyGraphAlgorithms (pybind11::module & m)
Referenced by PYBIND11_MODULE().
GeneratePyGraphs()
void GeneratePyGraphs (pybind11::module & m)
Referenced by PYBIND11_MODULE().
GeneratePyMolecule()
void GeneratePyMolecule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
GeneratePyParameterisedMolecule()
void GeneratePyParameterisedMolecule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
GeneratePyPeriodicTable()
void GeneratePyPeriodicTable (pybind11::module & m)
Referenced by PYBIND11_MODULE().
outstream_operator()
std::string outstream_operator (const T & t)