indigoX: indigox::algorithm Namespace Reference
indigox::algorithm Namespace Reference
Classes
struct access
struct ChargeGroupOptimiser
class CherryPicker
CherryPicker parameterisation algorithm class.
struct CherryPickerCallback
struct CMGCallback
struct CMGPrintCallback
class ConnectedSubgraphs
Generate connected subgraphs in G.
struct InternalCallback
class IXAStarOptimisation
class IXElectronAssigner
class IXLocalOptimisation
Local optimisation electron assignment algorithm.
struct MappingCallback
struct MGCallback
struct MGPrintCallback
class PriorityQueue
struct QueueItem
struct TraversalResults
Typedefs
using _ElectronAssigner = std::weak_ptr< IXElectronAssigner >
using AA_Settings = IXElectronAssigner::Settings
using AA_settings = IXElectronAssigner::Settings
using AAlgo = IXElectronAssigner::AssignAlgorithm
using algo = AssignerAlgorithm
using AS_settings = IXAStarOptimisation::Settings
using AssignerAlgorithm = IXElectronAssigner::AssignerAlgorithm
Type for the enum of available assignment algorithms.
using AssignMask = boost::dynamic_bitset<>
Type of the mask used for assignments.
using CMGE = graph::CMGEdge
using CMGS = graph::CondensedMolecularGraph
using CMGV = graph::CMGVertex
using CPSet = CherryPicker::Settings
using ElectronAssigner = std::shared_ptr< IXElectronAssigner >
using EParam = CherryPicker::EdgeParameters
using GL = graph::GraphLabel
using Heuristic = IXAStarOptimisation::Heuristic
using key_t = uint32_t
Type of the key for a score table.
using LO_Settings = IXLocalOptimisation::Settings
using LocMask = boost::dynamic_bitset<>
using Option = utils::Option
using queue_t = std::priority_queue< QueueItem, std::vector< QueueItem >, std::greater< QueueItem > >
using score_t = uint64_t
Type of the score of an electron assignment.
using ScoreTable = std::map< key_t, score_t >
Type of a score table.
using settings = IXElectronAssigner::Settings
using U = graph::Undirected
using VParam = CherryPicker::VertexParameters
Enumerations
enum SortOrder
Functions
std::string __PrintVertexName (const graph::AGVertex &v)
template<class V , class E , class S , class D , class VP , class EP , class Container >
int64_t AllCycles (graph::BaseGraph< V, E, S, D, VP, EP > &G, Container &ecycles)
template int64_t AllCycles (CondensedMolecularGraph::graph_type &, CondensedMolecularGraph::CycleEdgeContain &)
template int64_t AllCycles (MolecularGraph::graph_type &, MolecularGraph::CycleEdgeContain &)
template<class V , class E , class S , class D , class VP , class EP >
void AllSimplePaths (graph::BaseGraph< V, E, S, D, VP, EP > &G, V source, V target, std::vector< std::vector< E >> &paths, int64_t limit=-1)
Find all the simple paths between two vertices.
template void AllSimplePaths (CondensedMolecularGraph::graph_type &, CMGVertex, CMGVertex, std::vector< std::vector< CMGEdge >> &, int64_t)
template void AllSimplePaths (MolecularGraph::graph_type &, MGVertex, MGVertex, std::vector< std::vector< MGEdge >> &, int64_t)
template<class V , class E , class S , class D , class VP , class EP >
TraversalResults< V > BreadthFirstSearch (graph::BaseGraph< V, E, S, D, VP, EP > &G, V source=V(), int64_t limit=-1)
template TraversalResults< CMGVertex > BreadthFirstSearch (CondensedMolecularGraph::graph_type &, CMGVertex, int64_t)
template TraversalResults< MGVertex > BreadthFirstSearch (MolecularGraph::graph_type &, MGVertex, int64_t)
template<class V , class E , class S , class D , class VP , class EP , class Container >
int64_t ConnectedComponents (graph::BaseGraph< V, E, S, D, VP, EP > &G, Container &bits)
template int64_t ConnectedComponents (CondensedMolecularGraph::graph_type &, CondensedMolecularGraph::ComponentContain &)
template int64_t ConnectedComponents (MolecularGraph::graph_type &, MolecularGraph::ComponentContain &)
ElectronAssigner CreateElectronAssigner (const Molecule &m)
Create an ElectronAssigner.
template<class V , class E , class S , class D , class VP , class EP , class Container >
int64_t CycleBasis (graph::BaseGraph< V, E, S, D, VP, EP > &G, Container &basis)
template<>
int64_t CycleBasis (CondensedMolecularGraph::graph_type &G, CondensedMolecularGraph::CycleVertContain &basis)
template<>
int64_t CycleBasis (MolecularGraph::graph_type &G, MolecularGraph::CycleVertContain &basis)
template<>
int64_t CycleBasis (CondensedMolecularGraph::graph_type &G, CondensedMolecularGraph::CycleEdgeContain &basis)
template<>
int64_t CycleBasis (MolecularGraph::graph_type &G, MolecularGraph::CycleEdgeContain &basis)
template<class V , class E , class S , class D , class VP , class EP >
TraversalResults< V > DepthFirstSearch (graph::BaseGraph< V, E, S, D, VP, EP > &G, V source=V(), int64_t limit=-1)
Perform a breadth first search of G.
template TraversalResults< CMGVertex > DepthFirstSearch (CondensedMolecularGraph::graph_type &, CMGVertex, int64_t)
template TraversalResults< MGVertex > DepthFirstSearch (MolecularGraph::graph_type &, MGVertex, int64_t)
template<class V , class E , class S , class D , class VP , class EP >
int64_t ECycleBasis (BaseGraph< V, E, S, D, VP, EP > &G, typename BaseGraph< V, E, S, D, VP, EP >::CycleEdgeContain &e_basis)
SortOrder GetVertexSortOrder (const graph::AGVertex &v)
template<class V , class E , class S , class U , class VP , class EP >
size_t MinimalCycles (const graph::BaseGraph< V, E, S, U, VP, EP > &G, std::vector< std::vector< E *>> &min_cycles, bool strict=false)
Calculate a list of cycles which form a basis for cycles of G.
CherryPicker::VertexParameters operator & (CherryPicker::VertexParameters l, CherryPicker::VertexParameters r)
CherryPicker::EdgeParameters operator & (CherryPicker::EdgeParameters l, CherryPicker::EdgeParameters r)
CherryPicker::VertexParameters & operator &= (CherryPicker::VertexParameters &l, CherryPicker::VertexParameters r)
CherryPicker::EdgeParameters & operator &= (CherryPicker::EdgeParameters &l, CherryPicker::EdgeParameters r)
CherryPicker::VertexParameters operator| (CherryPicker::VertexParameters l, CherryPicker::VertexParameters r)
CherryPicker::EdgeParameters operator| (CherryPicker::EdgeParameters l, CherryPicker::EdgeParameters r)
CherryPicker::VertexParameters & operator|= (CherryPicker::VertexParameters &l, CherryPicker::VertexParameters r)
CherryPicker::EdgeParameters & operator|= (CherryPicker::EdgeParameters &l, CherryPicker::EdgeParameters r)
std::vector< std::vector< Atom > > OptimalChargeGroups (const Molecule &mol, int32_t limit=5)
template<class V , class E , class S , class D , class VP , class EP >
std::vector< E > ShortestPath (graph::BaseGraph< V, E, S, D, VP, EP > &G, V source, V target)
Find the shortest path between two vertices.
template std::vector< CMGEdge > ShortestPath (CondensedMolecularGraph::graph_type &, CMGVertex, CMGVertex)
template std::vector< MGEdge > ShortestPath (MolecularGraph::graph_type &, MGVertex, MGVertex)
void SubgraphIsomorphisms (graph::CondensedMolecularGraph &G1, graph::CondensedMolecularGraph &G2, CMGCallback &callback)
void SubgraphIsomorphisms (graph::MolecularGraph &G1, graph::MolecularGraph &G2, MGCallback &callback)
template<class V , class E , class S , class D , class VP , class EP >
void SubgraphIsomorphismsRunner (graph::BaseGraph< V, E, S, D, VP, EP > &G1, graph::BaseGraph< V, E, S, D, VP, EP > &G2, MappingCallback< V, E, S, D, VP, EP > &callback)
template<class V , class E , class S , class D , class VP , class EP >
int64_t VCycleBasis (BaseGraph< V, E, S, D, VP, EP > &G, typename BaseGraph< V, E, S, D, VP, EP >::CycleVertContain &basis)
Typedef Documentation
_ElectronAssigner
using _ElectronAssigner = std::weak_ptr<IXElectronAssigner>
AA_Settings
using AA_Settings = IXElectronAssigner::Settings
AA_settings
using AA_settings = IXElectronAssigner::Settings
AAlgo
using AAlgo = IXElectronAssigner::AssignAlgorithm
algo
using algo = AssignerAlgorithm
AS_settings
using AS_settings = IXAStarOptimisation::Settings
AssignerAlgorithm
using AssignerAlgorithm = IXElectronAssigner::AssignerAlgorithm
Type for the enum of available assignment algorithms.
AssignMask
using AssignMask = boost::dynamic_bitset<>
Type of the mask used for assignments.
CMGE
using CMGE = graph::CMGEdge
CMGS
using CMGS = graph::CondensedMolecularGraph
CMGV
using CMGV = graph::CMGVertex
CPSet
using CPSet = CherryPicker::Settings
ElectronAssigner
using ElectronAssigner = std::shared_ptr<IXElectronAssigner>
EParam
using EParam = CherryPicker::EdgeParameters
GL
using GL = graph::GraphLabel
Heuristic
using Heuristic = IXAStarOptimisation::Heuristic
key_t
using key_t = uint32_t
Type of the key for a score table.
LO_Settings
using LO_Settings = IXLocalOptimisation::Settings
LocMask
using LocMask = boost::dynamic_bitset<>
Option
typedef utils::Option Option
queue_t
using queue_t = std::priority_queue<QueueItem, std::vector<QueueItem>, std::greater<QueueItem> >
score_t
using score_t = uint64_t
Type of the score of an electron assignment.
ScoreTable
using ScoreTable = std::map<key_t, score_t>
Type of a score table.
settings
using settings = IXElectronAssigner::Settings
U
using U = graph::Undirected
VParam
using VParam = CherryPicker::VertexParameters
Enumeration Type Documentation
SortOrder
enum SortOrder strong
Enumerator
F_ONE
CL_ONE
BR_ONE
O_ONE
S_ONE
O_TWO
S_TWO
C_TWO_N_ONE
C_TWO_C_TWO
C_THREE_C_THREE
N_ONE
P_ONE
N_TWO
P_TWO
N_THREE
P_THREE
C_THREE_O_ONE
O_ONE_S_FOUR
C_THREE_S_ONE
O_ONE_P_FOUR
C_THREE_N_TWO
N_TWO_N_TWO
N_THREE_O_ONE
UNDEFINED
Function Documentation
__PrintVertexName()
std::string indigox::algorithm::__PrintVertexName (const graph::AGVertex & v)
Referenced by IXAStarOptimisation::Initalise(), and IXAStarOptimisation::Run().
AllCycles() [1/3]
int64_t AllCycles (graph::BaseGraph< V, E, S, D, VP, EP > & G, Container & ecycles)
Referenced by BaseGraph< CMGVertex, CMGEdge, CondensedMolecularGraph >::GetCycles(), and MinimalCycles().
AllCycles() [2/3]
template int64_t indigox::algorithm::AllCycles (CondensedMolecularGraph::graph_type & , CondensedMolecularGraph::CycleEdgeContain &)
AllCycles() [3/3]
template int64_t indigox::algorithm::AllCycles (MolecularGraph::graph_type & , MolecularGraph::CycleEdgeContain &)
AllSimplePaths() [1/3]
void AllSimplePaths (graph::BaseGraph< V, E, S, D, VP, EP > & G, V source, V target, std::vector< std::vector< E >> & paths, int64_t limit = -1)
Find all the simple paths between two vertices.
Determines all the paths between two vertices, using a modified depth-first search method. The order of the found paths is arbitary, though each path is ordered from source to target.
Parameters
G the graph to find paths in.
source the source vertex.
target the target vertex.
[out] paths vector to store all the found paths in.
limit the maximum length path to return.
Exceptions
std::runtime_error if you try something stupid.
AllSimplePaths() [2/3]
template void indigox::algorithm::AllSimplePaths (CondensedMolecularGraph::graph_type & , CMGVertex , CMGVertex , std::vector< std::vector< CMGEdge >> & , int64_t)
AllSimplePaths() [3/3]
template void indigox::algorithm::AllSimplePaths (MolecularGraph::graph_type & , MGVertex , MGVertex , std::vector< std::vector< MGEdge >> & , int64_t)
BreadthFirstSearch() [1/3]
TraversalResults< V > BreadthFirstSearch (graph::BaseGraph< V, E, S, D, VP, EP > & G, V source = V(), int64_t limit = -1)
BreadthFirstSearch() [2/3]
template TraversalResults<CMGVertex> indigox::algorithm::BreadthFirstSearch (CondensedMolecularGraph::graph_type & , CMGVertex , int64_t)
BreadthFirstSearch() [3/3]
template TraversalResults<MGVertex> indigox::algorithm::BreadthFirstSearch (MolecularGraph::graph_type & , MGVertex , int64_t)
ConnectedComponents() [1/3]
int64_t ConnectedComponents (graph::BaseGraph< V, E, S, D, VP, EP > & G, Container & bits)
Referenced by Athenaeum::AddAllFragments(), and BaseGraph< CMGVertex, CMGEdge, CondensedMolecularGraph >::GetConnectedComponents().
ConnectedComponents() [2/3]
template int64_t indigox::algorithm::ConnectedComponents (CondensedMolecularGraph::graph_type & , CondensedMolecularGraph::ComponentContain &)
ConnectedComponents() [3/3]
template int64_t indigox::algorithm::ConnectedComponents (MolecularGraph::graph_type & , MolecularGraph::ComponentContain &)
CreateElectronAssigner()
ElectronAssigner indigox::algorithm::CreateElectronAssigner (const Molecule & m) inline
Create an ElectronAssigner.
Friendship allows creation of electron assigner instances.
Parameters
m the molecule this electron assigner is for.
Returns
a new ElectronAssigner.
CycleBasis() [1/5]
int64_t indigox::algorithm::CycleBasis (graph::BaseGraph< V, E, S, D, VP, EP > & G, Container & basis)
Referenced by AllCycles(), and ECycleBasis().
CycleBasis() [2/5]
int64_t indigox::algorithm::CycleBasis (CondensedMolecularGraph::graph_type & G, CondensedMolecularGraph::CycleVertContain & basis)
CycleBasis() [3/5]
int64_t indigox::algorithm::CycleBasis (MolecularGraph::graph_type & G, MolecularGraph::CycleVertContain & basis)
CycleBasis() [4/5]
int64_t indigox::algorithm::CycleBasis (CondensedMolecularGraph::graph_type & G, CondensedMolecularGraph::CycleEdgeContain & basis)
CycleBasis() [5/5]
int64_t indigox::algorithm::CycleBasis (MolecularGraph::graph_type & G, MolecularGraph::CycleEdgeContain & basis)
DepthFirstSearch() [1/3]
TraversalResults< V > DepthFirstSearch (graph::BaseGraph< V, E, S, D, VP, EP > & G, V source = V(), int64_t limit = -1)
Perform a breadth first search of G.
Returns ordered vector of vertex pairs. Order is the order in which the vertices were discovered. First member of pair is the discovered vertex, second member is the predecessor of the discovered vertex. If no source is provided, the source is chosen arbitarily until all vertices have been discovered. If source is provided, only vertices within the component containing source will be searched. Limit is the limit of search depth.
Referenced by Molecule::PerceiveResidues().
DepthFirstSearch() [2/3]
template TraversalResults<CMGVertex> indigox::algorithm::DepthFirstSearch (CondensedMolecularGraph::graph_type & , CMGVertex , int64_t)
DepthFirstSearch() [3/3]
template TraversalResults<MGVertex> indigox::algorithm::DepthFirstSearch (MolecularGraph::graph_type & , MGVertex , int64_t)
ECycleBasis()
int64_t indigox::algorithm::ECycleBasis (BaseGraph< V, E, S, D, VP, EP > & G, typename BaseGraph< V, E, S, D, VP, EP >::CycleEdgeContain & e_basis)
Referenced by CycleBasis().
GetVertexSortOrder()
SortOrder indigox::algorithm::GetVertexSortOrder (const graph::AGVertex & v)
Referenced by IXAStarOptimisation::Initalise().
MinimalCycles()
size_t indigox::algorithm::MinimalCycles (const graph::BaseGraph< V, E, S, U, VP, EP > & G, std::vector< std::vector< E *>> & min_cycles, bool strict = false)
Calculate a list of cycles which form a basis for cycles of G.
A basis for cycles of a graph is a minimal collection of cycles such that any cycle in the graph can be written as a sum of cycles in the basis, where a summation of cycles is defined as an XOR of the edges. This is only implemented for Undirected graphs.
This implementation follows that of the networkx python library.
Template Parameters
V,E,VP,EP template parameters of the graph.
Parameters
G the graph to determine cycles of.
[out] paths vector of paths defining each member of cycle basis.
operator &() [1/2]
CherryPicker::VertexParameters indigox::algorithm::operator& (CherryPicker::VertexParameters l, CherryPicker::VertexParameters r) inline
operator &() [2/2]
CherryPicker::EdgeParameters indigox::algorithm::operator& (CherryPicker::EdgeParameters l, CherryPicker::EdgeParameters r) inline
operator &=() [1/2]
CherryPicker::VertexParameters& indigox::algorithm::operator&= (CherryPicker::VertexParameters & l, CherryPicker::VertexParameters r) inline
operator &=() [2/2]
CherryPicker::EdgeParameters& indigox::algorithm::operator&= (CherryPicker::EdgeParameters & l, CherryPicker::EdgeParameters r) inline
operator|() [1/2]
CherryPicker::VertexParameters indigox::algorithm::operator| (CherryPicker::VertexParameters l, CherryPicker::VertexParameters r) inline
operator|() [2/2]
CherryPicker::EdgeParameters indigox::algorithm::operator| (CherryPicker::EdgeParameters l, CherryPicker::EdgeParameters r) inline
operator|=() [1/2]
CherryPicker::VertexParameters& indigox::algorithm::operator|= (CherryPicker::VertexParameters & l, CherryPicker::VertexParameters r) inline
operator|=() [2/2]
CherryPicker::EdgeParameters& indigox::algorithm::operator|= (CherryPicker::EdgeParameters & l, CherryPicker::EdgeParameters r) inline
OptimalChargeGroups()
std::vector< std::vector< Atom > > OptimalChargeGroups (const Molecule & mol, int32_t limit = 5)
Referenced by Molecule::OptimiseChargeGroups().
ShortestPath() [1/3]
std::vector< E > ShortestPath (graph::BaseGraph< V, E, S, D, VP, EP > & G, V source, V target)
Find the shortest path between two vertices.
Determines the shortest path between two vertices, using a bi-directional breadth-first search method. If there is no path between the vertices, the returned path is empty. The path is returned has the vertices to traverse in order from the source to the target. Multiple short paths may exist. This function returns only one of them.
Template Parameters
GraphType the type of the graph.
Parameters
G the graph to find the path in.
source the source vertex.
target the target vertex.
Returns
the shortest path from source to target.
Exceptions
std::runtime_error if source and target are the same vertex or either of them is not part of the graph.
Referenced by Athenaeum::AddAllFragments(), and Residue::Impl::AminoAcidTest().
ShortestPath() [2/3]
template std::vector<CMGEdge> indigox::algorithm::ShortestPath (CondensedMolecularGraph::graph_type & , CMGVertex , CMGVertex)
ShortestPath() [3/3]
template std::vector<MGEdge> indigox::algorithm::ShortestPath (MolecularGraph::graph_type & , MGVertex , MGVertex)
SubgraphIsomorphisms() [1/2]
void SubgraphIsomorphisms (graph::CondensedMolecularGraph & G1, graph::CondensedMolecularGraph & G2, CMGCallback & callback)
Referenced by CherryPicker::ParameteriseMolecule().
SubgraphIsomorphisms() [2/2]
void SubgraphIsomorphisms (graph::MolecularGraph & G1, graph::MolecularGraph & G2, MGCallback & callback)
SubgraphIsomorphismsRunner()
void indigox::algorithm::SubgraphIsomorphismsRunner (graph::BaseGraph< V, E, S, D, VP, EP > & G1, graph::BaseGraph< V, E, S, D, VP, EP > & G2, MappingCallback< V, E, S, D, VP, EP > & callback)
Referenced by SubgraphIsomorphisms().
VCycleBasis()
int64_t indigox::algorithm::VCycleBasis (BaseGraph< V, E, S, D, VP, EP > & G, typename BaseGraph< V, E, S, D, VP, EP >::CycleVertContain & basis)
Referenced by CycleBasis().