indigoX: indigox Namespace Reference
indigox Namespace Reference
Namespaces
algorithm
graph
Namespace for all graph related functionality.
test
utils
utils namespace for useful utility functions
Classes
class _ElectronGraph
class _NTDecomp
class _PermutableGraph
class _TDecomp
class Angle
class Athenaeum
Athenaeum class for fragment storage in CherryPicker algorithm.
class Atom
class AtomIterator
class Bond
class Dihedral
class ElectronOpt
class Element
Read only class for storing elemental information.
struct ElnVertProp
class FFAngle
class FFAtom
class FFBond
class FFDihedral
class Forcefield
class Fragment
Fragment class for CherryPicker parameterisation algorithm.
class Molecule
struct NTDVertProp
class ParamAngle
class ParamAtom
class ParamBond
class ParamDihedral
class ParamMolecule
class PeriodicTable
Singleton class for storing and access elemental information.
struct PermVertProp
class Residue
struct TDVertProp
Typedefs
typedef utils::Graph< ElnVertProp > _ElnGraph
typedef utils::Graph< NTDVertProp, utils::NoProperty, utils::DirectedGraph > _NTDGraph
typedef utils::Graph< PermVertProp > _PermGraph
typedef utils::Graph< TDVertProp, utils::NoProperty, utils::UndirectedGraph > _TDGraph
using AngleType = FFAngle::Type
using AtomStereo = indigox::Atom::Stereo
Type for the stereochemistry enum of an atom.
using BondOrder = indigox::Bond::Order
Type for the order of a bond.
using BondStereo = indigox::Bond::Stereo
Type for the stereochemistry enum of a bond.
using BondType = FFBond::Type
using Data = CalculatedData
using DihedralType = FFDihedral::Type
typedef std::shared_ptr< _ElectronGraph > ElectronGraph
typedef std::vector< PermVertex > ElimOrder
typedef _ElnGraph::EdgeType ElnEdge
typedef _ElnGraph::EdgeIter ElnEdgeIter
typedef _ElnGraph::EdgeIterPair ElnEdgeIterPair
typedef _ElnGraph::NbrsIterPair ElnNbrsIterPair
typedef _ElnGraph::NbrsIter ElnNeighboursIter
typedef _ElnGraph::VertType ElnVertex
typedef _ElnGraph::VertIter ElnVertexIter
typedef _ElnGraph::VertIterPair ElnVertIterPair
using erow = std::pair< const Element &, int >
using FFFamily = Forcefield::Family
using FFParam = std::initializer_list< double >
type for collection of parameter inputs
typedef Options::AssignElectrons::FPT fpt_
typedef std::shared_ptr< _NTDecomp > NTDecomp
typedef _NTDGraph::EdgeType NTDEdge
typedef _NTDGraph::EdgeBool NTDEdgeBool
typedef _NTDGraph::EdgeIter NTDEdgeIter
typedef _NTDGraph::EdgeIterPair NTDEdgeIterPair
typedef _NTDGraph::NbrsIterPair NTDNbrsIterPair
typedef _NTDGraph::NbrsIter NTDNeighboursIter
typedef _NTDGraph::PredIter NTDPredecessorsIter
typedef _NTDGraph::PredIterPair NTDPredIterPair
typedef _NTDGraph::VertBool NTDVertBool
typedef _NTDGraph::VertType NTDVertex
typedef _NTDGraph::VertIter NTDVertexIter
typedef _NTDGraph::VertIterPair NTDVertIterPair
typedef _NTDGraph::VertTypePair NTDVertPair
typedef _PermGraph::EdgeIterPair PermEdgeIterPair
typedef _PermGraph::NbrsIter PermNbrsIter
typedef _PermGraph::NbrsIterPair PermNbrsIterPair
typedef std::shared_ptr< _PermutableGraph > PermutableGraph
typedef _PermGraph::VertType PermVertex
typedef _PermGraph::VertIter PermVertIter
typedef _PermGraph::VertIterPair PermVertIterPair
using ResidueType = Residue::Type
using sAthenaeum = std::shared_ptr< Athenaeum >
using sFragment = std::shared_ptr< Fragment >
using State = uint32_t
typedef std::shared_ptr< _TDecomp > TDecomp
typedef _TDGraph::EdgeType TDEdge
typedef _TDGraph::EdgeBool TDEdgeBool
typedef _TDGraph::EdgeIter TDEdgeIter
typedef _TDGraph::EdgeIterPair TDEdgeIterPair
typedef _TDGraph::NbrsIterPair TDNbrsIterPair
typedef _TDGraph::NbrsIter TDNeighboursIter
typedef _TDGraph::PredIter TDPredecessorsIter
typedef _TDGraph::PredIterPair TDPredIterPair
typedef _TDGraph::VertBool TDVertBool
typedef _TDGraph::VertType TDVertex
typedef _TDGraph::VertIter TDVertexIter
typedef _TDGraph::VertIterPair TDVertIterPair
typedef _TDGraph::VertTypePair TDVertPair
using wAthenaeum = std::weak_ptr< Athenaeum >
using wFragment = std::weak_ptr< Fragment >
Enumerations
enum CalculatedData : uint8_t
enum IteratorType
enum SortOrder
Functions
Fragment::OverlapType _GetOverType (const graph::CMGVertex &v, graph::CondensedMolecularGraph &g, std::vector< graph::CMGVertex > &)
void _MGVertexToCMGVertex (std::vector< graph::MGVertex > &v_in, std::vector< graph::CMGVertex > &v_out, graph::CondensedMolecularGraph &g)
template<class Iter >
double CalculateMean (Iter begin, Iter end)
Calculate the mean of a range of numbers.
template<class RandomIter >
double CalculateMedian (RandomIter begin, RandomIter end)
Calculate the median of a range of numbers.
template<class Iter >
double CalculateStandardDeviation (Iter begin, Iter end)
bool CanCutEdge (graph::CMGEdge &e, graph::CondensedMolecularGraph &g)
template<typename InputIter , typename T >
size_t Combinations (InputIter first, InputIter last, size_t r, std::vector< std::vector< T >> &out)
Forcefield GenerateGROMOS54A7 ()
const PeriodicTable & GetPeriodicTable ()
INDIGOX_SERIALISE (Angle)
INDIGOX_SERIALISE (Dihedral)
INDIGOX_SERIALISE (Bond)
INDIGOX_SERIALISE (Atom)
INDIGOX_SERIALISE (FFAtom)
INDIGOX_SERIALISE (Molecule)
INDIGOX_SERIALISE (Fragment)
INDIGOX_SERIALISE (FFAngle)
INDIGOX_SERIALISE (Athenaeum)
INDIGOX_SERIALISE (FFDihedral)
INDIGOX_SERIALISE (Forcefield)
Athenaeum LoadAthenaeum (std::string path)
Molecule LoadMolecule (std::string path)
std::ostream & operator<< (std::ostream &os, const Dihedral &dhd)
std::ostream & operator<< (std::ostream &os, const FFAtom &atm)
std::ostream & operator<< (std::ostream &os, const ParamAtom &atm)
std::ostream & operator<< (std::ostream &, const Element &)
std::ostream & operator<< (std::ostream &os, const Angle &ang)
std::ostream & operator<< (std::ostream &os, const ParamBond &bnd)
std::ostream & operator<< (std::ostream &os, const PeriodicTable &pt)
Print a PeriodicTable to an output stream.
std::ostream & operator<< (std::ostream &os, const Bond &bnd)
std::ostream & operator<< (std::ostream &os, const FFBond &bnd)
std::ostream & operator<< (std::ostream &os, const ParamAngle &ang)
std::ostream & operator<< (std::ostream &os, const FFAngle &ang)
std::ostream & operator<< (std::ostream &ss, erow er)
std::ostream & operator<< (std::ostream &os, const Atom &atm)
std::ostream & operator<< (std::ostream &os, const ParamDihedral &ang)
std::ostream & operator<< (std::ostream &os, const FFDihedral &dhd)
std::ostream & operator<< (std::ostream &os, const Fragment &frag)
std::ostream & operator<< (std::ostream &os, BondType type)
std::ostream & operator<< (std::ostream &os, AngleType type)
std::ostream & operator<< (std::ostream &os, DihedralType type)
std::ostream & operator<< (std::ostream &os, const Forcefield &ff)
void PeptideBonds (const graph::MolecularGraph &G, std::vector< graph::MGEdge > &edges)
std::string PeriodicTable_ToString ()
uint8_t PreplaceCount (const _MolecularGraph &G, MolVertex v)
uint8_t PreplaceCount (const _MolecularGraph &G, MolEdge e)
void SaveAthenaeum (const Athenaeum &ath, std::string path)
void SaveMolecule (const Molecule &mol, std::string path)
template<typename InputIt >
size_t sum_of_sizes (InputIt begin, InputIt end)
Typedef Documentation
_ElnGraph
typedef utils::Graph<ElnVertProp> _ElnGraph
_NTDGraph
typedef utils::Graph<NTDVertProp, utils::NoProperty, utils::DirectedGraph> _NTDGraph
_PermGraph
typedef utils::Graph<PermVertProp> _PermGraph
_TDGraph
typedef utils::Graph<TDVertProp, utils::NoProperty, utils::UndirectedGraph> _TDGraph
AngleType
using AngleType = FFAngle::Type
AtomStereo
using AtomStereo = indigox::Atom::Stereo
Type for the stereochemistry enum of an atom.
BondOrder
using BondOrder = indigox::Bond::Order
Type for the order of a bond.
BondStereo
using BondStereo = indigox::Bond::Stereo
Type for the stereochemistry enum of a bond.
BondType
using BondType = FFBond::Type
Data
using Data = CalculatedData
DihedralType
using DihedralType = FFDihedral::Type
ElectronGraph
typedef std::shared_ptr<_ElectronGraph> ElectronGraph
ElimOrder
typedef std::vector<PermVertex> ElimOrder
ElnEdge
typedef _ElnGraph::EdgeType ElnEdge
ElnEdgeIter
typedef _ElnGraph::EdgeIter ElnEdgeIter
ElnEdgeIterPair
typedef _ElnGraph::EdgeIterPair ElnEdgeIterPair
ElnNbrsIterPair
typedef _ElnGraph::NbrsIterPair ElnNbrsIterPair
ElnNeighboursIter
typedef _ElnGraph::NbrsIter ElnNeighboursIter
ElnVertex
typedef _ElnGraph::VertType ElnVertex
ElnVertexIter
typedef _ElnGraph::VertIter ElnVertexIter
ElnVertIterPair
typedef _ElnGraph::VertIterPair ElnVertIterPair
erow
using erow = std::pair<const Element &, int>
FFFamily
using FFFamily = Forcefield::Family
FFParam
using FFParam = std::initializer_list<double>
type for collection of parameter inputs
fpt_
typedef Options::AssignElectrons::FPT fpt_
NTDecomp
typedef std::shared_ptr<_NTDecomp> NTDecomp
NTDEdge
typedef _NTDGraph::EdgeType NTDEdge
NTDEdgeBool
typedef _NTDGraph::EdgeBool NTDEdgeBool
NTDEdgeIter
typedef _NTDGraph::EdgeIter NTDEdgeIter
NTDEdgeIterPair
typedef _NTDGraph::EdgeIterPair NTDEdgeIterPair
NTDNbrsIterPair
typedef _NTDGraph::NbrsIterPair NTDNbrsIterPair
NTDNeighboursIter
typedef _NTDGraph::NbrsIter NTDNeighboursIter
NTDPredecessorsIter
typedef _NTDGraph::PredIter NTDPredecessorsIter
NTDPredIterPair
typedef _NTDGraph::PredIterPair NTDPredIterPair
NTDVertBool
typedef _NTDGraph::VertBool NTDVertBool
NTDVertex
typedef _NTDGraph::VertType NTDVertex
NTDVertexIter
typedef _NTDGraph::VertIter NTDVertexIter
NTDVertIterPair
typedef _NTDGraph::VertIterPair NTDVertIterPair
NTDVertPair
typedef _NTDGraph::VertTypePair NTDVertPair
PermEdgeIterPair
typedef _PermGraph::EdgeIterPair PermEdgeIterPair
PermNbrsIter
typedef _PermGraph::NbrsIter PermNbrsIter
PermNbrsIterPair
typedef _PermGraph::NbrsIterPair PermNbrsIterPair
PermutableGraph
typedef std::shared_ptr<_PermutableGraph> PermutableGraph
PermVertex
typedef _PermGraph::VertType PermVertex
PermVertIter
typedef _PermGraph::VertIter PermVertIter
PermVertIterPair
typedef _PermGraph::VertIterPair PermVertIterPair
ResidueType
using ResidueType = Residue::Type
sAthenaeum
using sAthenaeum = std::shared_ptr<Athenaeum>
sFragment
using sFragment = std::shared_ptr<Fragment>
State
using State = uint32_t
TDecomp
typedef std::shared_ptr<_TDecomp> TDecomp
TDEdge
typedef _TDGraph::EdgeType TDEdge
TDEdgeBool
typedef _TDGraph::EdgeBool TDEdgeBool
TDEdgeIter
typedef _TDGraph::EdgeIter TDEdgeIter
TDEdgeIterPair
typedef _TDGraph::EdgeIterPair TDEdgeIterPair
TDNbrsIterPair
typedef _TDGraph::NbrsIterPair TDNbrsIterPair
TDNeighboursIter
typedef _TDGraph::NbrsIter TDNeighboursIter
TDPredecessorsIter
typedef _TDGraph::PredIter TDPredecessorsIter
TDPredIterPair
typedef _TDGraph::PredIterPair TDPredIterPair
TDVertBool
typedef _TDGraph::VertBool TDVertBool
TDVertex
typedef _TDGraph::VertType TDVertex
TDVertexIter
typedef _TDGraph::VertIter TDVertexIter
TDVertIterPair
typedef _TDGraph::VertIterPair TDVertIterPair
TDVertPair
typedef _TDGraph::VertTypePair TDVertPair
wAthenaeum
using wAthenaeum = std::weak_ptr<Athenaeum>
wFragment
using wFragment = std::weak_ptr<Fragment>
Enumeration Type Documentation
CalculatedData
enum CalculatedData : uint8_t strong
Enumerator
Formula
AnglePerception
DihedralPerception
ResiduePerception
ChargeGroupDetermination
CondensedGraph
Number
IteratorType
enum IteratorType
Enumerator
ATOM_NEIGHBOUR
BOND_ATOM
MOLECULE_ATOM
ATOM_BOND
MOLECULE_BOND
UNDEFINED
SortOrder
enum SortOrder strong
Enumerator
F_ONE
CL_ONE
BR_ONE
O_ONE
S_ONE
O_TWO
S_TWO
C_TWO_N_ONE
C_TWO_C_TWO
C_THREE_C_THREE
N_ONE
P_ONE
N_TWO
P_TWO
N_THREE
P_THREE
C_THREE_O_ONE
O_ONE_S_FOUR
C_THREE_S_ONE
O_ONE_P_FOUR
C_THREE_N_TWO
N_TWO_N_TWO
N_THREE_O_ONE
UNDEFINED
Function Documentation
_GetOverType()
Fragment::OverlapType indigox::_GetOverType (const graph::CMGVertex & v, graph::CondensedMolecularGraph & g, std::vector< graph::CMGVertex > &)
Referenced by Fragment::Fragment().
_MGVertexToCMGVertex()
void indigox::_MGVertexToCMGVertex (std::vector< graph::MGVertex > & v_in, std::vector< graph::CMGVertex > & v_out, graph::CondensedMolecularGraph & g)
Referenced by Fragment::Fragment().
CalculateMean()
double indigox::CalculateMean (Iter begin, Iter end)
Calculate the mean of a range of numbers.
Template Parameters
Iter type of the iterator defining the range.
Parameters
begin,end iterators defining the range.
Returns
the mean of the range.
Referenced by CalculateStandardDeviation(), and ParamAtom::MeanCharge().
CalculateMedian()
double indigox::CalculateMedian (RandomIter begin, RandomIter end)
Calculate the median of a range of numbers.
If the range has an odd length, the median is the middle item in the sorted range. If it has an even length, the median is the mean of the two central items. If the range is empty, the median is undefined.
Template Parameters
RandomIter random access itertor defining the range.
Parameters
begin,end iterators defining the range.
Returns
the median of the range.
Exceptions
std::runtime_error if the range is empty.
Referenced by ParamAtom::MeadianCharge().
CalculateStandardDeviation()
double indigox::CalculateStandardDeviation (Iter begin, Iter end)
Referenced by ParamAtom::StandardDeviationCharge().
CanCutEdge()
bool indigox::CanCutEdge (graph::CMGEdge & e, graph::CondensedMolecularGraph & g)
Referenced by Athenaeum::AddAllFragments().
Combinations()
size_t indigox::Combinations (InputIter first, InputIter last, size_t r, std::vector< std::vector< T >> & out)
Referenced by indigox::algorithm::AllCycles().
GenerateGROMOS54A7()
Forcefield GenerateGROMOS54A7 ()
GetPeriodicTable()
const PeriodicTable & GetPeriodicTable ()
Referenced by Benzene(), GenerateGROMOS54A7(), FFAtom::GetElement(), IXElectronAssigner::LoadScoreTable(), Molecule::NewAtom(), PeriodicTable_ToString(), ProtonatedLysine(), Atom::Reset(), Atom::Impl::serialise(), and Atom::SetElement().
INDIGOX_SERIALISE() [1/11]
indigox::INDIGOX_SERIALISE (Angle)
INDIGOX_SERIALISE() [2/11]
indigox::INDIGOX_SERIALISE (Dihedral)
INDIGOX_SERIALISE() [3/11]
indigox::INDIGOX_SERIALISE (Bond)
INDIGOX_SERIALISE() [4/11]
indigox::INDIGOX_SERIALISE (Atom)
INDIGOX_SERIALISE() [5/11]
indigox::INDIGOX_SERIALISE (FFAtom)
INDIGOX_SERIALISE() [6/11]
indigox::INDIGOX_SERIALISE (Molecule)
INDIGOX_SERIALISE() [7/11]
indigox::INDIGOX_SERIALISE (Fragment)
INDIGOX_SERIALISE() [8/11]
indigox::INDIGOX_SERIALISE (FFAngle)
INDIGOX_SERIALISE() [9/11]
indigox::INDIGOX_SERIALISE (Athenaeum)
INDIGOX_SERIALISE() [10/11]
indigox::INDIGOX_SERIALISE (FFDihedral)
INDIGOX_SERIALISE() [11/11]
indigox::INDIGOX_SERIALISE (Forcefield)
LoadAthenaeum()
Athenaeum LoadAthenaeum (std::string path)
LoadMolecule()
Molecule LoadMolecule (std::string path)
Referenced by main().
operator<<() [1/20]
std::ostream & operator<< (std::ostream & os, const Dihedral & dhd)
operator<<() [2/20]
std::ostream& indigox::operator<< (std::ostream & os, const FFAtom & atm)
operator<<() [3/20]
std::ostream& indigox::operator<< (std::ostream & os, const ParamAtom & atm)
operator<<() [4/20]
std::ostream & operator<< (std::ostream & os, const Element & element)
operator<<() [5/20]
std::ostream& indigox::operator<< (std::ostream & os, const Angle & ang)
operator<<() [6/20]
std::ostream& indigox::operator<< (std::ostream & os, const ParamBond & bnd)
operator<<() [7/20]
std::ostream & operator<< (std::ostream & os, const PeriodicTable & pt)
Print a PeriodicTable to an output stream.
Prints number of elements in the PeriodicTable.
Parameters
os output stream to print to.
pt PeriodicTable to print.
Returns
the output stream.
operator<<() [8/20]
std::ostream& indigox::operator<< (std::ostream & os, const Bond & bnd)
operator<<() [9/20]
std::ostream& indigox::operator<< (std::ostream & os, const FFBond & bnd)
operator<<() [10/20]
std::ostream& indigox::operator<< (std::ostream & os, const ParamAngle & ang)
operator<<() [11/20]
std::ostream& indigox::operator<< (std::ostream & os, const FFAngle & ang)
operator<<() [12/20]
std::ostream& indigox::operator<< (std::ostream & ss, erow er)
operator<<() [13/20]
std::ostream& indigox::operator<< (std::ostream & os, const Atom & atm)
operator<<() [14/20]
std::ostream& indigox::operator<< (std::ostream & os, const ParamDihedral & ang)
operator<<() [15/20]
std::ostream& indigox::operator<< (std::ostream & os, const FFDihedral & dhd)
operator<<() [16/20]
std::ostream& indigox::operator<< (std::ostream & os, const Fragment & frag)
operator<<() [17/20]
std::ostream & operator<< (std::ostream & os, BondType type)
operator<<() [18/20]
std::ostream & operator<< (std::ostream & os, AngleType type)
operator<<() [19/20]
std::ostream & operator<< (std::ostream & os, DihedralType type)
operator<<() [20/20]
std::ostream& indigox::operator<< (std::ostream & os, const Forcefield & ff)
PeptideBonds()
void indigox::PeptideBonds (const graph::MolecularGraph & G, std::vector< graph::MGEdge > & edges)
Referenced by Molecule::PerceiveResidues().
PeriodicTable_ToString()
std::string indigox::PeriodicTable_ToString ()
Referenced by operator<<().
PreplaceCount() [1/2]
uint8_t indigox::PreplaceCount (const _MolecularGraph & G, MolVertex v)
Referenced by _ElectronGraph::_ElectronGraph().
PreplaceCount() [2/2]
uint8_t indigox::PreplaceCount (const _MolecularGraph & G, MolEdge e)
SaveAthenaeum()
void SaveAthenaeum (const Athenaeum & ath, std::string path)
SaveMolecule()
void SaveMolecule (const Molecule & mol, std::string path)
sum_of_sizes()
size_t indigox::sum_of_sizes (InputIt begin, InputIt end)
Referenced by Forcefield::NumAngleTypes(), Forcefield::NumBondTypes(), and Forcefield::NumDihedralTypes().