indigoX: indigox::graph Namespace Reference
indigox::graph Namespace Reference
Namespace for all graph related functionality.
Namespaces
BaseGraph
Classes
class BaseGraph
Template base class for all graphs used in the indigoX library.
class CMGEdge
Class for the edges of an IXCondensedMolecularGraph.
class CMGVertex
Class for the vertices of an IXCondensedMolecularGraph.
class CondensedMolecularGraph
struct Directed
Type for specifying that a graph is directed.
struct GraphLabel
Type for applying a numerical label to a vertex or edge.
class IXAGVertex
Class for the vertices of an IXAssignmentGraph.
class IXAssignmentGraph
Class used to assign electrons to a molecule.
class MGEdge
Class for the edges of a IXMolecularGraph.
class MGVertex
Class for the vertices of a IXMolecularGraph.
class MolecularGraph
Class containing a graph representation of a molecule.
struct Undirected
Type for specifying that a graph is undirected.
Typedefs
using _AGVertex = std::weak_ptr< IXAGVertex >
using _AssignmentGraph = std::weak_ptr< IXAssignmentGraph >
using AGVertex = std::shared_ptr< IXAGVertex >
using AssignmentGraph = std::shared_ptr< IXAssignmentGraph >
using ContractedSymmetry = CMGVertex::ContractedSymmetry
using EdgeIsoMask = eastl::bitset< 14, uint16_t >
type used to store the isomorphism testing mask for IXCMGEdge.
using VertexIsoMask = eastl::bitset< 37, uint64_t >
type used to store the isomorphism testing mask for IXCMGVertex.
Functions
CMGVertex::ContractedSymmetry __get_symmetry (size_t atomic_number, const MGVertex &)
uint32_t __VertexPrePlace (size_t degree, const Element &element)
CondensedMolecularGraph Condense (const MolecularGraph &G)
INDIGOX_SERIALISE (MGVertex)
INDIGOX_SERIALISE (MGEdge)
INDIGOX_SERIALISE (MolecularGraph)
INDIGOX_SERIALISE (CMGVertex)
INDIGOX_SERIALISE (CMGEdge)
INDIGOX_SERIALISE (CondensedMolecularGraph)
std::ostream & operator<< (std::ostream &os, const MGVertex &v)
std::ostream & operator<< (std::ostream &os, const MGEdge &e)
std::ostream & operator<< (std::ostream &os, const MolecularGraph &G)
std::ostream & operator<< (std::ostream &os, const CMGVertex &v)
std::ostream & operator<< (std::ostream &os, const CMGEdge &e)
std::ostream & operator<< (std::ostream &os, const CondensedMolecularGraph &G)
Variables
eastl::vector_set< Element > __con_elem
Detailed Description
Namespace for all graph related functionality.
Typedef Documentation
_AGVertex
using _AGVertex = std::weak_ptr<IXAGVertex>
_AssignmentGraph
using _AssignmentGraph = std::weak_ptr<IXAssignmentGraph>
AGVertex
using AGVertex = std::shared_ptr<IXAGVertex>
AssignmentGraph
using AssignmentGraph = std::shared_ptr<IXAssignmentGraph>
ContractedSymmetry
using ContractedSymmetry = CMGVertex::ContractedSymmetry
EdgeIsoMask
using EdgeIsoMask = eastl::bitset<14, uint16_t>
type used to store the isomorphism testing mask for IXCMGEdge.
VertexIsoMask
using VertexIsoMask = eastl::bitset<37, uint64_t>
type used to store the isomorphism testing mask for IXCMGVertex.
Function Documentation
__get_symmetry()
CMGVertex::ContractedSymmetry indigox::graph::__get_symmetry (size_t atomic_number, const MGVertex &)
Referenced by CMGVertex::CMGVertex(), and CMGVertex::IsContractedHere().
__VertexPrePlace()
uint32_t indigox::graph::__VertexPrePlace (size_t degree, const Element & element)
Referenced by IXAssignmentGraph::PreassignElectrons().
Condense()
CondensedMolecularGraph Condense (const MolecularGraph & G)
Referenced by MolecularGraph::GetCondensedGraph(), Molecule::GetCondensedGraph(), and CherryPicker::ParameteriseMolecule().
INDIGOX_SERIALISE() [1/6]
indigox::graph::INDIGOX_SERIALISE (MGVertex)
INDIGOX_SERIALISE() [2/6]
indigox::graph::INDIGOX_SERIALISE (MGEdge)
INDIGOX_SERIALISE() [3/6]
indigox::graph::INDIGOX_SERIALISE (MolecularGraph)
INDIGOX_SERIALISE() [4/6]
indigox::graph::INDIGOX_SERIALISE (CMGVertex)
INDIGOX_SERIALISE() [5/6]
indigox::graph::INDIGOX_SERIALISE (CMGEdge)
INDIGOX_SERIALISE() [6/6]
indigox::graph::INDIGOX_SERIALISE (CondensedMolecularGraph)
operator<<() [1/6]
std::ostream& indigox::graph::operator<< (std::ostream & os, const MGVertex & v)
operator<<() [2/6]
std::ostream& indigox::graph::operator<< (std::ostream & os, const MGEdge & e)
operator<<() [3/6]
std::ostream& indigox::graph::operator<< (std::ostream & os, const MolecularGraph & G)
operator<<() [4/6]
std::ostream& indigox::graph::operator<< (std::ostream & os, const CMGVertex & v)
operator<<() [5/6]
std::ostream& indigox::graph::operator<< (std::ostream & os, const CMGEdge & e)
operator<<() [6/6]
std::ostream& indigox::graph::operator<< (std::ostream & os, const CondensedMolecularGraph & G)
Variable Documentation
__con_elem
eastl::vector_set<Element> __con_elem
Initial value:
= {
      GetPeriodicTable().GetElement("H"), GetPeriodicTable().GetElement("F"),
      GetPeriodicTable().GetElement("Cl"), GetPeriodicTable().GetElement("Br"),
      GetPeriodicTable().GetElement("I")}
Referenced by CMGVertex::CMGVertex(), and Condense().