indigoX: python.io.parser Namespace Reference
python.io.parser Namespace Reference
Functions
def LoadFragmentFile (path, ff)
def LoadIFPFile (path)
Loads a GROMOS IFP file as a forcefield.
def LoadITPFile (path, ff, details=None)
def LoadIXDFile (path, mol)
def LoadMTBFile (path, ff, details=None)
def LoadParameterisedMolecule (coord_path, param_path, ff, details=None)
def LoadPDBFile (path, details=None)
Loads the given PDB file into a Molecule.
Variables
list __all__
Function Documentation
LoadFragmentFile()
def python.io.parser.LoadFragmentFile (path, ff)
LoadIFPFile()
def python.io.parser.LoadIFPFile (path)
Loads a GROMOS IFP file as a forcefield.
See the GROMOS Manual for definition of the IFP file format.
Parameters
path the path to the IFP file
Returns
the loaded forcefield
LoadITPFile()
def python.io.parser.LoadITPFile (path, ff, details = None)
Referenced by python.io.parser.LoadParameterisedMolecule().
LoadIXDFile()
def python.io.parser.LoadIXDFile (path, mol)
Referenced by python.io.parser.LoadITPFile(), python.io.parser.LoadMTBFile(), and python.io.parser.LoadPDBFile().
LoadMTBFile()
def python.io.parser.LoadMTBFile (path, ff, details = None)
Referenced by python.io.parser.LoadParameterisedMolecule().
LoadParameterisedMolecule()
def python.io.parser.LoadParameterisedMolecule (coord_path, param_path, ff, details = None)
Referenced by python.io.parser.LoadFragmentFile().
LoadPDBFile()
def python.io.parser.LoadPDBFile (path, details = None)
Loads the given PDB file into a Molecule.
Returns
the loaded molecule
Referenced by python.io.parser.LoadParameterisedMolecule().
Variable Documentation
__all__
list __all__ private
Initial value:
 =  ["LoadIFPFile", "LoadPDBFile", "LoadMTBFile", "LoadIXDFile",
            "LoadParameterisedMolecule", "LoadITPFile" , "LoadFragmentFile"]